/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-09-27 15:57:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <title>Salon Management System</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel='stylesheet prefetch' href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900|RobotoDraft:400,100,300,500,700,900'>\r\n");
      out.write("    <link rel='stylesheet prefetch' href='font-awesome/css/font-awesome.css'>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline}article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section{display:block}body{line-height:1}ol,ul{list-style:none}blockquote,q{quotes:none}blockquote:before,blockquote:after,q:before,q:after{content:'';content:none}table{border-collapse:collapse;border-spacing:0}\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background: #e9e9e9;\r\n");
      out.write("            color: #666666;\r\n");
      out.write("            font-family: 'RobotoDraft', 'Roboto', sans-serif;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            -webkit-font-smoothing: antialiased;\r\n");
      out.write("            -moz-osx-font-smoothing: grayscale;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Pen Title */\r\n");
      out.write("        .pen-title {\r\n");
      out.write("            padding: 50px 0;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            letter-spacing: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        .pen-title h1 {\r\n");
      out.write("            margin: 0 0 20px;\r\n");
      out.write("            font-size: 48px;\r\n");
      out.write("            font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("        .pen-title span {\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        .pen-title span .fa {\r\n");
      out.write("            color: #ed2553;\r\n");
      out.write("        }\r\n");
      out.write("        .pen-title span a {\r\n");
      out.write("            color: #ed2553;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Rerun */\r\n");
      out.write("        .rerun {\r\n");
      out.write("            margin: 0 0 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .rerun a {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            background: #ed2553;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            -webkit-transition: 0.3s ease;\r\n");
      out.write("            transition: 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .rerun a:hover {\r\n");
      out.write("            box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Scroll To Bottom */\r\n");
      out.write("        #codepen, #portfolio {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            bottom: 30px;\r\n");
      out.write("            right: 30px;\r\n");
      out.write("            background: #363636;\r\n");
      out.write("            width: 56px;\r\n");
      out.write("            height: 56px;\r\n");
      out.write("            border-radius: 100%;\r\n");
      out.write("            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);\r\n");
      out.write("            -webkit-transition: 0.3s ease;\r\n");
      out.write("            transition: 0.3s ease;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        #codepen i, #portfolio i {\r\n");
      out.write("            line-height: 56px;\r\n");
      out.write("        }\r\n");
      out.write("        #codepen:hover, #portfolio:hover {\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* CodePen */\r\n");
      out.write("        #portfolio {\r\n");
      out.write("            bottom: 96px;\r\n");
      out.write("            right: 36px;\r\n");
      out.write("            background: #ed2553;\r\n");
      out.write("            width: 44px;\r\n");
      out.write("            height: 44px;\r\n");
      out.write("            -webkit-animation: buttonFadeInUp 1s ease;\r\n");
      out.write("            animation: buttonFadeInUp 1s ease;\r\n");
      out.write("        }\r\n");
      out.write("        #portfolio i {\r\n");
      out.write("            line-height: 44px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Container */\r\n");
      out.write("        .container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            max-width: 460px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin: 0 auto 100px;\r\n");
      out.write("        }\r\n");
      out.write("        .container.active .card:first-child {\r\n");
      out.write("            background: #f2f2f2;\r\n");
      out.write("            margin: 0 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .container.active .card:nth-child(2) {\r\n");
      out.write("            background: #fafafa;\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .container.active .card.alt {\r\n");
      out.write("            top: 20px;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            min-width: 100%;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            padding: 60px 0 40px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .container.active .card.alt .toggle {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 40px;\r\n");
      out.write("            right: -70px;\r\n");
      out.write("            box-shadow: none;\r\n");
      out.write("            -webkit-transform: scale(10);\r\n");
      out.write("            transform: scale(10);\r\n");
      out.write("            -webkit-transition: -webkit-transform .3s ease;\r\n");
      out.write("            transition: -webkit-transform .3s ease;\r\n");
      out.write("            transition: transform .3s ease;\r\n");
      out.write("            transition: transform .3s ease, -webkit-transform .3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .container.active .card.alt .toggle:before {\r\n");
      out.write("            content: '';\r\n");
      out.write("        }\r\n");
      out.write("        .container.active .card.alt .title,\r\n");
      out.write("        .container.active .card.alt .input-container,\r\n");
      out.write("        .container.active .card.alt .button-container {\r\n");
      out.write("            left: 0;\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            visibility: visible;\r\n");
      out.write("            -webkit-transition: .3s ease;\r\n");
      out.write("            transition: .3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .container.active .card.alt .title {\r\n");
      out.write("            -webkit-transition-delay: .3s;\r\n");
      out.write("            transition-delay: .3s;\r\n");
      out.write("        }\r\n");
      out.write("        .container.active .card.alt .input-container {\r\n");
      out.write("            -webkit-transition-delay: .4s;\r\n");
      out.write("            transition-delay: .4s;\r\n");
      out.write("        }\r\n");
      out.write("        .container.active .card.alt .input-container:nth-child(2) {\r\n");
      out.write("            -webkit-transition-delay: .5s;\r\n");
      out.write("            transition-delay: .5s;\r\n");
      out.write("        }\r\n");
      out.write("        .container.active .card.alt .input-container:nth-child(3) {\r\n");
      out.write("            -webkit-transition-delay: .6s;\r\n");
      out.write("            transition-delay: .6s;\r\n");
      out.write("        }\r\n");
      out.write("        .container.active .card.alt .button-container {\r\n");
      out.write("            -webkit-transition-delay: .7s;\r\n");
      out.write("            transition-delay: .7s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Card */\r\n");
      out.write("        .card {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            padding: 60px 0 40px 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);\r\n");
      out.write("            -webkit-transition: .3s ease;\r\n");
      out.write("            transition: .3s ease;\r\n");
      out.write("            /* Title */\r\n");
      out.write("            /* Inputs */\r\n");
      out.write("            /* Button */\r\n");
      out.write("            /* Footer */\r\n");
      out.write("            /* Alt Card */\r\n");
      out.write("        }\r\n");
      out.write("        .card:first-child {\r\n");
      out.write("            background: #fafafa;\r\n");
      out.write("            height: 10px;\r\n");
      out.write("            border-radius: 5px 5px 0 0;\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .card .title {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            border-left: 5px solid #4a148c;\r\n");
      out.write("            margin: 0 0 35px;\r\n");
      out.write("            padding: 10px 0 10px 50px;\r\n");
      out.write("            color: #4a148c;\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("        }\r\n");
      out.write("        .card .input-container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            margin: 0 60px 50px;\r\n");
      out.write("        }\r\n");
      out.write("        .card .input-container input {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            background: none;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            border: 0;\r\n");
      out.write("            color: #212121;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("        }\r\n");
      out.write("        .card .input-container input:focus ~ label {\r\n");
      out.write("            color: #9d9d9d;\r\n");
      out.write("            -webkit-transform: translate(-12%, -50%) scale(0.75);\r\n");
      out.write("            transform: translate(-12%, -50%) scale(0.75);\r\n");
      out.write("        }\r\n");
      out.write("        .card .input-container input:focus ~ .bar:before, .card .input-container input:focus ~ .bar:after {\r\n");
      out.write("            width: 50%;\r\n");
      out.write("        }\r\n");
      out.write("        .card .input-container input:valid ~ label {\r\n");
      out.write("            color: #9d9d9d;\r\n");
      out.write("            -webkit-transform: translate(-12%, -50%) scale(0.75);\r\n");
      out.write("            transform: translate(-12%, -50%) scale(0.75);\r\n");
      out.write("        }\r\n");
      out.write("        .card .input-container label {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            color: #757575;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            font-weight: 300;\r\n");
      out.write("            line-height: 60px;\r\n");
      out.write("            -webkit-transition: 0.2s ease;\r\n");
      out.write("            transition: 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .card .input-container .bar {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            background: #757575;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 1px;\r\n");
      out.write("        }\r\n");
      out.write("        .card .input-container .bar:before, .card .input-container .bar:after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background: #6a1b9a;\r\n");
      out.write("            width: 0;\r\n");
      out.write("            height: 2px;\r\n");
      out.write("            -webkit-transition: .2s ease;\r\n");
      out.write("            transition: .2s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .card .input-container .bar:before {\r\n");
      out.write("            left: 50%;\r\n");
      out.write("        }\r\n");
      out.write("        .card .input-container .bar:after {\r\n");
      out.write("            right: 50%;\r\n");
      out.write("        }\r\n");
      out.write("        .card .button-container {\r\n");
      out.write("            margin: 0 60px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .card .button-container button {\r\n");
      out.write("            outline: 0;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            background: 0;\r\n");
      out.write("            width: 240px;\r\n");
      out.write("            border: 2px solid #e3e3e3;\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            line-height: 1;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            -webkit-transition: .3s ease;\r\n");
      out.write("            transition: .3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .card .button-container button span {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            color: #ddd;\r\n");
      out.write("            -webkit-transition: .3s ease;\r\n");
      out.write("            transition: .3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .card .button-container button:before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            display: block;\r\n");
      out.write("            background: #4a148c;\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            border-radius: 100%;\r\n");
      out.write("            margin: -15px 0 0 -15px;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            -webkit-transition: .3s ease;\r\n");
      out.write("            transition: .3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .card .button-container button:hover, .card .button-container button:active, .card .button-container button:focus {\r\n");
      out.write("            border-color: #6a1b9a;\r\n");
      out.write("        }\r\n");
      out.write("        .card .button-container button:hover span, .card .button-container button:active span, .card .button-container button:focus span {\r\n");
      out.write("            color: #6a1b9a;\r\n");
      out.write("        }\r\n");
      out.write("        .card .button-container button:active span, .card .button-container button:focus span {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        .card .button-container button:active:before, .card .button-container button:focus:before {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            -webkit-transform: scale(10);\r\n");
      out.write("            transform: scale(10);\r\n");
      out.write("        }\r\n");
      out.write("        .card .footer {\r\n");
      out.write("            margin: 40px 0 0;\r\n");
      out.write("            color: #d3d3d3;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            font-weight: 300;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .card .footer a {\r\n");
      out.write("            color: inherit;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            -webkit-transition: .3s ease;\r\n");
      out.write("            transition: .3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .card .footer a:hover {\r\n");
      out.write("            color: #bababa;\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 40px;\r\n");
      out.write("            right: -70px;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("            width: 140px;\r\n");
      out.write("            height: 140px;\r\n");
      out.write("            background: none;\r\n");
      out.write("            border-radius: 100%;\r\n");
      out.write("            box-shadow: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            -webkit-transition: .3s ease;\r\n");
      out.write("            transition: .3s ease;\r\n");
      out.write("            /* Toggle */\r\n");
      out.write("            /* Title */\r\n");
      out.write("            /* Input */\r\n");
      out.write("            /* Button */\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .toggle {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            background: #7b1fa2;\r\n");
      out.write("            width: 140px;\r\n");
      out.write("            height: 140px;\r\n");
      out.write("            border-radius: 100%;\r\n");
      out.write("            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 58px;\r\n");
      out.write("            line-height: 140px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .toggle:before {\r\n");
      out.write("            content: '\\f06e';\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font: normal normal normal 14px/1 FontAwesome;\r\n");
      out.write("            font-size: inherit;\r\n");
      out.write("            text-rendering: auto;\r\n");
      out.write("            -webkit-font-smoothing: antialiased;\r\n");
      out.write("            -moz-osx-font-smoothing: grayscale;\r\n");
      out.write("            -webkit-transform: translate(0, 0);\r\n");
      out.write("            transform: translate(0, 0);\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .title,\r\n");
      out.write("        .card.alt .input-container,\r\n");
      out.write("        .card.alt .button-container {\r\n");
      out.write("            left: 100px;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            visibility: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .title {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            border-color: #ffffff;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .title .close {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            right: 60px;\r\n");
      out.write("            display: inline;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 58px;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .title .close:before {\r\n");
      out.write("            content: '\\00d7';\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .input-container input {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .input-container input:focus ~ label {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .input-container input:focus ~ .bar:before, .card.alt .input-container input:focus ~ .bar:after {\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .input-container input:valid ~ label {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .input-container label {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .input-container .bar {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .button-container button {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            border-color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .button-container button span {\r\n");
      out.write("            color: #6a1b9a;\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .button-container button:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("        }\r\n");
      out.write("        .card.alt .button-container button:active:before, .card.alt .button-container button:focus:before {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Keyframes */\r\n");
      out.write("        @-webkit-keyframes buttonFadeInUp {\r\n");
      out.write("            0% {\r\n");
      out.write("                bottom: 30px;\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes buttonFadeInUp {\r\n");
      out.write("            0% {\r\n");
      out.write("                bottom: 30px;\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body translate=\"no\" >\r\n");
      out.write("<div class=\"pen-title\">\r\n");
      out.write("    <h1>Salon Management System</h1>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"card\"></div>\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h1 class=\"title\">Login</h1>\r\n");
      out.write("        <form method=\"post\" action=\"login\">\r\n");
      out.write("            <div class=\"input-container\">\r\n");
      out.write("                <input type=\"text\" id=\"username\" name=\"username\" required=\"required\"/>\r\n");
      out.write("                <label for=\"username\">Username</label>\r\n");
      out.write("                <div class=\"bar\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-container\">\r\n");
      out.write("                <input type=\"password\" id=\"password\" name=\"pass\" required=\"required\"/>\r\n");
      out.write("                <label for=\"password\">Password</label>\r\n");
      out.write("                <div class=\"bar\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"button-container\">\r\n");
      out.write("                <button type=\"submit\" value=\"Submit\"><span>Go</span></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer\"><a href=\"#\">Forgot your password?</a></div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card alt\">\r\n");
      out.write("        <div class=\"toggle\"></div>\r\n");
      out.write("        <h1 class=\"title\">Guest\r\n");
      out.write("            <div class=\"close\"></div>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <form style=\"height: 350px !important;\">\r\n");
      out.write("            <div class=\"button-container\">\r\n");
      out.write("                <button href=\"#\" style=\"margin-top: 120px !important;\"><span>Continue</span></button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $('.toggle').on('click', function() {\r\n");
      out.write("        $('.container').stop().addClass('active');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('.close').on('click', function() {\r\n");
      out.write("        $('.container').stop().removeClass('active');\r\n");
      out.write("    });\r\n");
      out.write("    //# sourceURL=pen.js\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
