/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-08-17 04:56:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class baseLayout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005furl_0026_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fparam_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fparam_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction.release();
    _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.release();
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/materialize.css\"/>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/mystyle.css\"/>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/mtnc-emp.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bartstable.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/material.min.css\"/>\r\n");
      out.write("    <!-- <link type=\"text/css\" rel=\"stylesheet\" href=\"css/mtnc-catalogue.css\"/> -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/dropify.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/sweetalert.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/mainloader.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/animate.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/angular-datatables.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/baselayout.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/perfect-scrollbar.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <!--<link rel=\"stylesheet\" type=\"text/css\" href=\"css/drag.css\"/>-->\r\n");
      out.write("    <!--<link rel=\"stylesheet\" type=\"text/css\" href=\"css/animate.css\"/>-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--Let browser know website is optimized for mobile-->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("    <title>\r\n");
      out.write("        ");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"purple lighten-5 demo\" ng-app = \"app\">\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("    <header class=\"headnav\">\r\n");
      out.write("        <ul id=\"slide-out\" class=\"side-nav fixed z-depth-0\">\r\n");
      out.write("            <li class=\"user-details\" style=\"height: 64px !important; background-color: #212121 !important;\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col col s4 m4 l4\" style=\"padding: 5px !important;\">\r\n");
      out.write("                            <img src=\"");
      if (_jspx_meth_s_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("                                 alt=\"\" class=\"circle responsive-img valign profile-image\"\r\n");
      out.write("                                 style=\"width: 50px !important; height: 50px !important; margin-left: 10px !important;\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col col s8 m8 l8\">\r\n");
      out.write("                            <ul id=\"profile-dropdown\" class=\"dropdown-content\"\r\n");
      out.write("                                style=\"margin-top: 55px !important; overflow-y: hidden !important; margin-left: -15px !important;\">\r\n");
      out.write("                                <li><a href=\"#\" style=\"padding-top: 12px !important;\"><i\r\n");
      out.write("                                        class=\"mdi-action-face-unlock\"></i>\r\n");
      out.write("                                    Profile</a></li>\r\n");
      out.write("                                <li><a href=\"#\" style=\"padding-top: 12px !important;\"><i\r\n");
      out.write("                                        class=\"mdi-action-settings\"></i>\r\n");
      out.write("                                    Settings</a></li>\r\n");
      out.write("                                <li><a href=\"#\" style=\"padding-top: 12px !important;\"><i\r\n");
      out.write("                                        class=\"mdi-communication-live-help\"></i> Help</a></li>\r\n");
      out.write("                                <li class=\"divider\"></li>\r\n");
      out.write("                                <li><a href=\"#\" style=\"padding-top: 12px !important;\"><i\r\n");
      out.write("                                        class=\"mdi-action-lock-outline\"></i> Lock</a></li>\r\n");
      out.write("                                <li><a href=\"logout\" style=\"padding-top: 12px !important;\"><i\r\n");
      out.write("                                        class=\"mdi-hardware-keyboard-tab\"></i> Logout</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a class=\"truncate btn-flat dropdown-button waves-effect waves-light white-text profile-btn\"\r\n");
      out.write("                               href=\"#\"\r\n");
      out.write("                               data-activates=\"profile-dropdown\"\r\n");
      out.write("                               style=\"margin-top: 10px !important; margin-left: -15px !important; padding-right: 0px !important;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<i\r\n");
      out.write("                                    class=\"material-icons right\">arrow_drop_down</i></a>\r\n");
      out.write("                            <!--<p class=\"user-roal\">Administrator</p>-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <!--<div class=\"center\">-->\r\n");
      out.write("            <!--<img src=\"");
      if (_jspx_meth_s_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"-->\r\n");
      out.write("            <!--class=\"circle\" style=\"width: 150px; height: 150px; margin-top: 10px; margin-bottom: 5px;\">-->\r\n");
      out.write("            <!--<a href=\"\" style=\"padding: 0px !important;\"></a>-->\r\n");
      out.write("            <!--<a href=\"logout\" style=\"padding: 0px !important;\">Logout</a>-->\r\n");
      out.write("            <!--</div>-->\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"collapsible\" data-collapsible=\"accordion\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"collapsible-header\" href=\"login\"><i\r\n");
      out.write("                            class=\"material-icons\">home</i><b>Home</b></a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!--  <li class=\"no-padding\"> -->\r\n");
      out.write("            <ul class=\"collapsible\" id=\"mtnc\" data-collapsible=\"accordion\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"collapsible-header\"><i class=\"material-icons\">build</i><b>Maintenance</b></a>\r\n");
      out.write("                    <div class=\"collapsible-body\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"employeeMaintenance\">Employee</a></li>\r\n");
      out.write("                            <li><a href=\"productMaintenance\">Product</a></li>\r\n");
      out.write("                            <li><a href=\"serviceMaintenance\">Service</a></li>\r\n");
      out.write("                            <li><a href=\"packageMaintenance\">Package</a></li>\r\n");
      out.write("                            <li><a href=\"locationMaintenance\">Delivery Charge</a></li>\r\n");
      out.write("                            <li><a href=\"extraChargeMaintenance\">Other Charge</a></li>\r\n");
      out.write("                            <li><a href=\"promoMaintenance\">Promo</a></li>\r\n");
      out.write("                            <li><a href=\"discountMaintenance\">Discount</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"collapsible-header\"><i class=\"material-icons\">shopping_cart</i><b>Transaction</b></a>\r\n");
      out.write("                    <div class=\"collapsible-body\">\r\n");
      out.write("                        <ul class=\"navul\">\r\n");
      out.write("                            <li><a href=\"getInventory\">Inventory</a></li>\r\n");
      out.write("                            <li><a href=\"transWalkIn\">Walk In</a></li>\r\n");
      out.write("                            <li><a href=\"transReserve\">Reservation</a></li>\r\n");
      out.write("                            <li><a href=\"productsales\">Product Sales</a></li>\r\n");
      out.write("                            <li><a href=\"paymentTransaction\">Payment</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"collapsible\" data-collapsible=\"accordion\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"collapsible-header\"><i class=\"material-icons\">search</i><b>Queries</b></a>\r\n");
      out.write("                    <div class=\"collapsible-body\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"employeeQueries\">Employee</a></li>\r\n");
      out.write("                            <li><a href=\"\">Product</a></li>\r\n");
      out.write("                            <li><a href=\"\">Service</a></li>\r\n");
      out.write("                            <li><a href=\"\">Package</a></li>\r\n");
      out.write("                            <li><a href=\"\">Delivery Charge</a></li>\r\n");
      out.write("                            <li><a href=\"\">Other Charge</a></li>\r\n");
      out.write("                            <li><a href=\"\">Promo</a></li>\r\n");
      out.write("                            <li><a href=\"\">Discount</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"collapsible\" data-collapsible=\"accordion\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"collapsible-header\" href=\"admin-home.jsp\"><i\r\n");
      out.write("                            class=\"material-icons\">settings</i><b>Utilities</b></a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"collapsible\" data-collapsible=\"accordion\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"collapsible-header\" href=\"admin-home.jsp\"><i\r\n");
      out.write("                            class=\"material-icons\">assessment</i><b>Reports</b></a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <article>\r\n");
      out.write("        <nav class=\"z-depth-0\">\r\n");
      out.write("            <div class=\"nav-wrapper purple darken-4\">\r\n");
      out.write("                <a href=\"#\" class=\"brand-logo center purple-text text-lighten-5 \">Salon Management System</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div id=\"loader-wrapper\">\r\n");
      out.write("            <div id=\"loader\"></div>\r\n");
      out.write("            <div class=\"loader-section section-left\"></div>\r\n");
      out.write("            <div class=\"loader-section section-right\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
      if (_jspx_meth_tiles_005finsertAttribute_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Import jQuery before materialize.js-->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/materialize.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/angular.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/angular-animate.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/angular-datatables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bartstable.js\"></script>\r\n");
      out.write("<!--<script type=\"text/javascript\" src=\"js/picker.date.js\"></script>-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/maintenance-emp.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/additional.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/validation.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/stepform.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.formatter.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/dropify.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/sweetalert.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/angular-SweetAlert.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ellipsis.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/priceformat.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/formatted-numbers.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.formatCurrency-1.4.0.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/moment-with-locale.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.ellipsis.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/lodash.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"js/ProductsSales/ajax.js\"></script> -->\r\n");
      out.write("<!-- jQuery Ajax -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ajax/extracharge.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ajax/package.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ajax/package-view.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ajax/package-update.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ajax/package-deactivate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ajax/promo.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ajax/promo-update.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ajax/promo-update-func.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/perfect-scrollbar.jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/baselayout.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/angular-resource.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/angular-checklist.js\"></script>\r\n");
      out.write("<!--<script type=\"text/javascript\" src=\"js/angular-materialize.min.js\"></script>-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Angular imports -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/main.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/payment/payment.ctr.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/payment/payment.fac.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/walkin/walkin.ctr.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/walkin/walkin.fac.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/prodsales/locationfactory.fac.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/prodsales/prodSales.ctrl.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/reservation/reservationFactory.fac.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/reservation/reservation.ctrl.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/reservation/reservation-table.ctrl.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/queries/queryFactory.fac.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"app/queries/employee/empQueryController.ctrl.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f0.setParent(null);
    // /tiles/baseLayout.jsp(30,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f0.setName("title");
    // /tiles/baseLayout.jsp(30,8) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f0.setIgnore(true);
    int _jspx_eval_tiles_005finsertAttribute_005f0 = _jspx_th_tiles_005finsertAttribute_005f0.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f0 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005faction.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f0.setParent(null);
    // /tiles/baseLayout.jsp(41,38) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f0.setAction("getImage");
    int _jspx_eval_s_005furl_005f0 = _jspx_th_s_005furl_005f0.doStartTag();
    if (_jspx_eval_s_005furl_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005furl_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005furl_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005furl_005f0.doInitBody();
      }
      do {
        if (_jspx_meth_s_005fparam_005f0(_jspx_th_s_005furl_005f0, _jspx_page_context))
          return true;
        if (_jspx_meth_s_005fparam_005f1(_jspx_th_s_005furl_005f0, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_s_005furl_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005furl_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005faction.reuse(_jspx_th_s_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction.reuse(_jspx_th_s_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005furl_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:param
    org.apache.struts2.views.jsp.ParamTag _jspx_th_s_005fparam_005f0 = (org.apache.struts2.views.jsp.ParamTag) _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.get(org.apache.struts2.views.jsp.ParamTag.class);
    _jspx_th_s_005fparam_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005furl_005f0);
    // /tiles/baseLayout.jsp(41,63) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fparam_005f0.setName("ImageID");
    int _jspx_eval_s_005fparam_005f0 = _jspx_th_s_005fparam_005f0.doStartTag();
    if (_jspx_eval_s_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fparam_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fparam_005f0.doInitBody();
      }
      do {
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        int evalDoAfterBody = _jspx_th_s_005fparam_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fparam_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.reuse(_jspx_th_s_005fparam_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.reuse(_jspx_th_s_005fparam_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005furl_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:param
    org.apache.struts2.views.jsp.ParamTag _jspx_th_s_005fparam_005f1 = (org.apache.struts2.views.jsp.ParamTag) _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.get(org.apache.struts2.views.jsp.ParamTag.class);
    _jspx_th_s_005fparam_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005furl_005f0);
    // /tiles/baseLayout.jsp(41,115) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fparam_005f1.setName("type");
    int _jspx_eval_s_005fparam_005f1 = _jspx_th_s_005fparam_005f1.doStartTag();
    if (_jspx_eval_s_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fparam_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fparam_005f1.doInitBody();
      }
      do {
        out.write("employee");
        int evalDoAfterBody = _jspx_th_s_005fparam_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fparam_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.reuse(_jspx_th_s_005fparam_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.reuse(_jspx_th_s_005fparam_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f1 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005faction.get(org.apache.struts2.views.jsp.URLTag.class);
    _jspx_th_s_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005furl_005f1.setParent(null);
    // /tiles/baseLayout.jsp(72,26) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005furl_005f1.setAction("getImage");
    int _jspx_eval_s_005furl_005f1 = _jspx_th_s_005furl_005f1.doStartTag();
    if (_jspx_eval_s_005furl_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005furl_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005furl_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005furl_005f1.doInitBody();
      }
      do {
        if (_jspx_meth_s_005fparam_005f2(_jspx_th_s_005furl_005f1, _jspx_page_context))
          return true;
        if (_jspx_meth_s_005fparam_005f3(_jspx_th_s_005furl_005f1, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_s_005furl_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005furl_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005furl_0026_005faction.reuse(_jspx_th_s_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction.reuse(_jspx_th_s_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fparam_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005furl_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:param
    org.apache.struts2.views.jsp.ParamTag _jspx_th_s_005fparam_005f2 = (org.apache.struts2.views.jsp.ParamTag) _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.get(org.apache.struts2.views.jsp.ParamTag.class);
    _jspx_th_s_005fparam_005f2.setPageContext(_jspx_page_context);
    _jspx_th_s_005fparam_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005furl_005f1);
    // /tiles/baseLayout.jsp(72,51) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fparam_005f2.setName("ImageID");
    int _jspx_eval_s_005fparam_005f2 = _jspx_th_s_005fparam_005f2.doStartTag();
    if (_jspx_eval_s_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fparam_005f2.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fparam_005f2.doInitBody();
      }
      do {
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        int evalDoAfterBody = _jspx_th_s_005fparam_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fparam_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fparam_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.reuse(_jspx_th_s_005fparam_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.reuse(_jspx_th_s_005fparam_005f2);
    return false;
  }

  private boolean _jspx_meth_s_005fparam_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005furl_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:param
    org.apache.struts2.views.jsp.ParamTag _jspx_th_s_005fparam_005f3 = (org.apache.struts2.views.jsp.ParamTag) _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.get(org.apache.struts2.views.jsp.ParamTag.class);
    _jspx_th_s_005fparam_005f3.setPageContext(_jspx_page_context);
    _jspx_th_s_005fparam_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005furl_005f1);
    // /tiles/baseLayout.jsp(72,103) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fparam_005f3.setName("type");
    int _jspx_eval_s_005fparam_005f3 = _jspx_th_s_005fparam_005f3.doStartTag();
    if (_jspx_eval_s_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fparam_005f3.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fparam_005f3.doInitBody();
      }
      do {
        out.write("employee");
        int evalDoAfterBody = _jspx_th_s_005fparam_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fparam_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fparam_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.reuse(_jspx_th_s_005fparam_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fparam_0026_005fname.reuse(_jspx_th_s_005fparam_005f3);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f1 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f1.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f1.setParent(null);
    // /tiles/baseLayout.jsp(159,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f1.setName("body");
    int _jspx_eval_tiles_005finsertAttribute_005f1 = _jspx_th_tiles_005finsertAttribute_005f1.doStartTag();
    if (_jspx_th_tiles_005finsertAttribute_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f1);
    return false;
  }
}
