/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-08-17 00:31:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gss.model.Package;
import com.gss.model.ProductPackage;
import com.gss.model.ServicePackage;
import com.gss.model.Service;
import com.gss.model.Product;
import java.util.List;

public final class maintenance_002dpackage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"wrapper\">\n");
      out.write("    <div class=\"main z-depth-barts\" style=\"margin-left: 20px; margin-right: 20px;\">\n");
      out.write("        <div class=\"col s12\" style=\"margin-left: 20px; margin-right: 20px;\">\n");
      out.write("            <h3 class=\"grey-text text-darken-1\">Package Maintenance</h3>\n");
      out.write("            <a class=\"createPackbtn z-depth-1 hoverable waves-effect waves-light modal-trigger btn purple darken-2 left white-text\"\n");
      out.write("               href=\"#createPackageModal\" style=\"margin-top: 30px; margin-left: 15px;\"><i\n");
      out.write("                    class=\"material-icons\">add</i></a>\n");
      out.write("            <a class=\"z-depth-1 hoverable waves-effect waves-light modal-viewall btn purple darken-2 left white-text\"\n");
      out.write("               href=\"#archivePackageModal\" style=\"margin-top: 30px; margin-left: 15px;\"><i class=\"material-icons\">archive</i></a>\n");
      out.write("            <nav class=\"right white hoverable  z-depth-1\" style=\"width: 300px; margin-right: 20px;\">\n");
      out.write("                <div class=\"nav-wrapper col s4\">\n");
      out.write("                    <form>\n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <input id=\"packageSearch\" placeholder=\"Search\" class=\"grey-text text-darken-4\" type=\"search\">\n");
      out.write("                            <label for=\"packageSearch\"><i\n");
      out.write("                                    class=\"material-icons grey-text text-darken-4\">search</i></label>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("\n");
      out.write("            <table id=\"packagetbl\"\n");
      out.write("                   class=\"hoverable z-depth-1 cell-border row-border display centered responsive-table highlight\"\n");
      out.write("                   cellspacing=\"0\" width=\"100%\"\n");
      out.write("                   style=\"border: 1px solid #bdbdbd; padding: 10px; margin-top: -30px !important;\" rowspan=\"10\">\n");
      out.write("                <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th class=\"dt-head-left\">Package Name</th>\n");
      out.write("                    <th class=\"dt-head-left\">Type</th>\n");
      out.write("                    <th class=\"dt-head-left\">Description</th>\n");
      out.write("                    <th align=\"center\" class=\"no-sort\">Action</th>\n");
      out.write("                </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tfoot style=\"border: 1px solid #bdbdbd;\">\n");
      out.write("                <tr>\n");
      out.write("                    <th class=\"dt-head-left\">Package Name</th>\n");
      out.write("                    <th class=\"dt-head-left\">Type</th>\n");
      out.write("                    <th class=\"dt-head-left\">Description</th>\n");
      out.write("                    <th align=\"center\" class=\"no-sort\">Action</th>\n");
      out.write("                </tr>\n");
      out.write("                </tfoot>\n");
      out.write("\n");
      out.write("                <tbody>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div id=\"archivePackageModal\" class=\"modal modal-fixed-footer\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"col s12\" style=\"margin-left: 20px; margin-right: 20px;\">\n");
      out.write("                <h4 class=\"grey-text text-darken-1 center\">Archive</h4>\n");
      out.write("                <nav class=\"right white hoverable  z-depth-1\" style=\"width: 300px; margin-right: 20px;\">\n");
      out.write("                    <div class=\"nav-wrapper col s4\">\n");
      out.write("                        <form>\n");
      out.write("                            <div class=\"input-field\">\n");
      out.write("                                <input id=\"archivePackageSearch\" placeholder=\"Search\" class=\"grey-text text-darken-4\" type=\"search\">\n");
      out.write("                                <label for=\"archivePackageSearch\"><i\n");
      out.write("                                        class=\"material-icons grey-text text-darken-4\">search</i></label>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("\n");
      out.write("                <table id=\"archivePackageTbl\"\n");
      out.write("                       class=\"hoverable z-depth-1 cell-border row-border display centered responsive-table highlight\"\n");
      out.write("                       cellspacing=\"0\" width=\"100%\"\n");
      out.write("                       style=\"border: 1px solid #bdbdbd; padding: 10px; margin-top: -30px !important;\" rowspan=\"10\">\n");
      out.write("                    <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th class=\"dt-head-left\">Package Name</th>\n");
      out.write("                        <th class=\"dt-head-left\">Type</th>\n");
      out.write("                        <th class=\"dt-head-left\">Description</th>\n");
      out.write("                        <th align=\"center\" class=\"no-sort\">Action</th>\n");
      out.write("                    </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tfoot style=\"border: 1px solid #bdbdbd;\">\n");
      out.write("                    <tr>\n");
      out.write("                        <th class=\"dt-head-left\">Package Name</th>\n");
      out.write("                        <th class=\"dt-head-left\">Type</th>\n");
      out.write("                        <th class=\"dt-head-left\">Description</th>\n");
      out.write("                        <th align=\"center\" class=\"no-sort\">Action</th>\n");
      out.write("                    </tr>\n");
      out.write("                    </tfoot>\n");
      out.write("\n");
      out.write("                    <tbody>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("            <a class=\"modal-action modal-close waves-effect waves-purple btn-flat transparent\" >CLOSE</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- end view product and service modal -->\n");
      out.write("\n");
      out.write("    <div id=\"viewModalPackage\" class=\"modal\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <h4 class=\"center grey-text text-darken-1\">View Package</h4>\n");
      out.write("            <div class=\"wrapper\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div id=\"viewContainer\">\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Modal Structure -->\n");
      out.write("    <div id=\"createPackageModal\" class=\"modal modal-fixed-footer\">\n");
      out.write("        <form id=\"createPackageForm\" class=\"col s12 form\" method=\"post\" action=\"createPackage\"\n");
      out.write("              enctype=\"multipart/form-data\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"wrapper\">\n");
      out.write("                    <h4 class=\"center grey-text text-darken-1\">Create Package<a id=\"btnCrPackageExit\" type=\"reset\"\n");
      out.write("                                                                                value=\"Reset\"\n");
      out.write("                                                                                class=\"modal-action modal-close\"><i\n");
      out.write("                            class=\"small material-icons right grey-text text-darken-4\">close</i></a></h4>\n");
      out.write("                    <div class=\"progress\">\n");
      out.write("                        <div class=\"determinate center active purple darken-4 white-text\" role=\"progressbar\"\n");
      out.write("                             aria-valuemin=\"0\"\n");
      out.write("                             aria-valuemax=\"100\" style=\"color: white;\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"crpackageerrorcontainer card red center input-field col s12 white-text z-depth-barts\">\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"steppack well\" style=\"margin-top: 20px;\">\n");
      out.write("                        <div class=\"wrapper\">\n");
      out.write("                            <div class=\"row form-group\">\n");
      out.write("                                <div class=\"container\">\n");
      out.write("                                    <div class=\"input-field col s12\">\n");
      out.write("                                        <input name=\"strPackageName\" id=\"crPackageName\" type=\"text\"\n");
      out.write("                                               class=\"validate\" placeholder=\"Package Name\"/>\n");
      out.write("                                        <label for=\"crPackageName\" class=\"active\" id=\"label1\"><b>Package Name</b><i\n");
      out.write("                                                class=\"material-icons red-text tiny\">error_outline</i></label>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"input-field col s12\" style=\"margin-top: 10px !important;\">\n");
      out.write("                                    <textarea name=\"strPackageDesc\" id=\"crPackageDesc\" type=\"text\"\n");
      out.write("                                              class=\"materialize-textarea\" length=\"80\"\n");
      out.write("                                              placeholder=\"Description\"\n");
      out.write("                                              style=\"margin-top: -10px !important;\"></textarea>\n");
      out.write("                                        <label for=\"crPackageDesc\" class=\"active\"><b>Description</b><i\n");
      out.write("                                                class=\"material-icons red-text tiny\">error_outline</i></label>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"input-field col s12\">\n");
      out.write("                                        <select name=\"intPackageType\" id=\"crPackageType\" multiple required>\n");
      out.write("                                            <option disabled value=\"default\">Choose your option</option>\n");
      out.write("                                            <option value=\"1\">Event</option>\n");
      out.write("                                            <option value=\"2\">Home Service</option>\n");
      out.write("                                            <option value=\"3\">Walk-In</option>\n");
      out.write("                                        </select>\n");
      out.write("                                        <label for=\"crPackageType\"><b>Type</b><i\n");
      out.write("                                                class=\"material-icons red-text tiny\">error_outline</i></label>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"steppack well\">\n");
      out.write("                        <div class=\"row form-group\">\n");
      out.write("                            <div class=\"col s4\">\n");
      out.write("                                <select name=\"\" id=\"packageFilter\">\n");
      out.write("                                    <option value=\"product\" selected>Product</option>\n");
      out.write("                                    <option value=\"service\">Service</option>\n");
      out.write("                                </select>\n");
      out.write("                                <label for=\"packageFilter\"><b>Select</b></label>\n");
      out.write("                            </div>\n");
      out.write("                            <nav class=\"right white z-depth-1\" style=\"width: 300px; margin-right: 20px;\">\n");
      out.write("                                <div class=\"nav-wrapper col s12\">\n");
      out.write("                                    <form>\n");
      out.write("                                        <div class=\"input-field\">\n");
      out.write("                                            <input id=\"crpackageSearch\" placeholder=\"Search\"\n");
      out.write("                                                   class=\"grey-text text-darken-4\"\n");
      out.write("                                                   type=\"search\" style=\"border: none !important;\">\n");
      out.write("                                            <label for=\"crpackageSearch\"><i\n");
      out.write("                                                    class=\"material-icons grey-text text-darken-4\">search</i></label>\n");
      out.write("                                        </div>\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                            </nav>\n");
      out.write("                            <div class=\"col s12\">\n");
      out.write("                                <ul class=\"collapsible\" data-collapsible=\"accordion\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <div class=\"collapsible-header\" id=\"listheadcollapsible\"><i\n");
      out.write("                                                class=\"material-icons\">view_list</i>List\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"collapsible-body\" id=\"listcollapsible\"\n");
      out.write("                                             style=\"margin:0px 0px 0px 0px !important; padding: 0px 0px 0px 0px !important;\">\n");
      out.write("                                            <div class=\"tablewrapper\">\n");
      out.write("                                                <table id=\"crpacktblProd\"\n");
      out.write("                                                       class=\"cell-border row-border display centered responsive-table highlight\"\n");
      out.write("                                                       cellspacing=\"0\" width=\"100%\"\n");
      out.write("                                                       style=\"border: 1px solid #bdbdbd; margin-top: -30px !important;\"\n");
      out.write("                                                       rowspan=\"5\">\n");
      out.write("                                                    <thead>\n");
      out.write("                                                    <tr>\n");
      out.write("                                                        <th class=\"dt-head-center no-sort\">Select</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Name</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Category</th>\n");
      out.write("                                                        <th class=\"dt-head-right\">Price</th>\n");
      out.write("                                                        <th align=\"dt-head-right\" class=\"no-sort\">Quantity</th>\n");
      out.write("                                                    </tr>\n");
      out.write("                                                    </thead>\n");
      out.write("                                                    <tfoot style=\"border: 1px solid #bdbdbd;\">\n");
      out.write("                                                    <tr>\n");
      out.write("                                                        <th class=\"dt-head-center no-sort\">Select</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Name</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Category</th>\n");
      out.write("                                                        <th class=\"dt-head-right\">Price</th>\n");
      out.write("                                                        <th align=\"dt-head-right\" class=\"no-sort\">Quantity</th>\n");
      out.write("                                                    </tr>\n");
      out.write("                                                    </tfoot>\n");
      out.write("\n");
      out.write("                                                    <tbody>\n");
      out.write("                                                    </tbody>\n");
      out.write("                                                </table>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"tablewrapper\">\n");
      out.write("                                                <table id=\"crpacktblServ\"\n");
      out.write("                                                       class=\"cell-border row-border display centered responsive-table highlight\"\n");
      out.write("                                                       cellspacing=\"0\" width=\"100%\"\n");
      out.write("                                                       style=\"border: 1px solid #bdbdbd; margin-top: -30px !important;\"\n");
      out.write("                                                       rowspan=\"5\">\n");
      out.write("                                                    <thead>\n");
      out.write("                                                    <tr>\n");
      out.write("                                                        <th class=\"dt-head-center no-sort\">Select</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Name</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Category</th>\n");
      out.write("                                                        <th class=\"dt-head-right\">Price</th>\n");
      out.write("                                                        <th align=\"dt-head-right\" class=\"no-sort\">Quantity</th>\n");
      out.write("                                                    </tr>\n");
      out.write("                                                    </thead>\n");
      out.write("                                                    <tfoot style=\"border: 1px solid #bdbdbd;\">\n");
      out.write("                                                    <tr>\n");
      out.write("                                                        <th class=\"dt-head-center no-sort\">Select</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Name</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Category</th>\n");
      out.write("                                                        <th class=\"dt-head-right\">Price</th>\n");
      out.write("                                                        <th align=\"dt-head-right\" class=\"no-sort\">Quantity</th>\n");
      out.write("                                                    </tr>\n");
      out.write("                                                    </tfoot>\n");
      out.write("\n");
      out.write("                                                    <tbody>\n");
      out.write("                                                    </tbody>\n");
      out.write("                                                </table>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col s9 z-depth-barts white prodservlist\" id=\"prodservContainer\">\n");
      out.write("                                <h6 class=\"center\" style=\"padding-top: -2px !important;\"><b>Selected Items</b></h6>\n");
      out.write("                                <div class=\"col s12\" id=\"pslist\"\n");
      out.write("                                     style=\"margin-top: -13px !important; margin-bottom: 5px !important;\"></div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col s3\">\n");
      out.write("                                <div class=\"input-field col s12\">\n");
      out.write("                                    <input type=\"text\" class=\"right-align grey-text text-darken-3\" disabled name=\"\"\n");
      out.write("                                           id=\"crPackTotal\" placeholder=\"Price\"/>\n");
      out.write("                                    <label for=\"crPackTotal\" class=\"active grey-text text-darken-3\"><b>Total</b></label>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"input-field col s12\" style=\"margin-top: 20px !important;\">\n");
      out.write("                                    <input type=\"text\" class=\"right-align prodPrice\" name=\"createPackagePrice\" id=\"crPackPrice\"\n");
      out.write("                                           placeholder=\"Price\" required/>\n");
      out.write("                                    <label for=\"crPackPrice\" class=\"active\"><b>Price</b><i\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <!--<div class=\"col s12 z-depth-barts white prodservlist\" style=\"margin-top: 5px;\"-->\n");
      out.write("                            <!--id=\"servContainer\">-->\n");
      out.write("                            <!--<h6 class=\"center\" style=\"padding-top: -2px !important;\"><b>Service List</b></h6>-->\n");
      out.write("                            <!--<div class=\"col s6\" id=\"servList\"-->\n");
      out.write("                            <!--style=\"margin-top: -13px !important; margin-bottom: 5px !important;\"></div>-->\n");
      out.write("                            <!--</div>-->\n");
      out.write("\n");
      out.write("                            <!--<input type=\"submit\" value=\"create\"/>-->\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button class=\"red-text btn-flat transparent left\" disabled\n");
      out.write("                        style=\"margin:0px !important; padding:0px !important;\"><i\n");
      out.write("                        class=\"material-icons\">error_outline</i>&nbspRequired field\n");
      out.write("                </button>\n");
      out.write("                <button type=\"button\" id=\"backbtn\"\n");
      out.write("                        class=\"actionpack backformpack waves-effect waves-purple transparent btn-flat\"\n");
      out.write("                        style=\"margin-left: 3px;margin-right:3px;\">BACK\n");
      out.write("                </button>\n");
      out.write("                <button type=\"button\" id=\"nextbtn\"\n");
      out.write("                        class=\"actionpack nextformpack waves-effect waves-light white-text btn-flat purple\"\n");
      out.write("                        style=\"margin-left: 3px; margin-right:3px;\">NEXT\n");
      out.write("                </button>\n");
      out.write("                <button type=\"submit\" value=\"submit\" id=\"createSubmitForm\" disabled onclick=\"createPackage()\"\n");
      out.write("                        class=\"actionpack submitformpack waves-effect waves-light white-text btn-flat purple\"\n");
      out.write("                        style=\"margin-left:3px; margin-right:3px; opacity: 0.3 !important;\">CREATE\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div id=\"updatePackageModal\" class=\"updatePackageModal modal modal-fixed-footer\">\n");
      out.write("        <div class=\"loadingbarts\" id=\"packageloadingupdate\"> <!-- mystyle.css -->\n");
      out.write("            <span class=\"centerer\"></span>\n");
      out.write("            <img class=\"salonlogo circle\" src=\"./img/logo.png\" height=\"200\"/>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form class=\"col s12\" id=\"updatePackageForm\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"wrapper\">\n");
      out.write("                    <h4 class=\"center grey-text text-darken-1\">Update Package<a id=\"btnUpdatePackageExit\"\n");
      out.write("                                                                                type=\"reset\"\n");
      out.write("                                                                                value=\"Reset\"\n");
      out.write("                                                                                class=\"btnUpdatePackageExit modal-action modal-close\"><i\n");
      out.write("                            class=\"small material-icons right grey-text text-darken-4\">close</i></a></h4>\n");
      out.write("                    <div class=\"updatepackageerror center input-field col s12 card red white-text z-depth-barts\"\n");
      out.write("                         style=\"margin-top: -10px !important;\">\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col s12\">\n");
      out.write("                            <ul class=\"tabs tab-demo-active\" style=\"width: 100%; background-color: #fafafa;\">\n");
      out.write("                                <li class=\"tab col s6\"><a\n");
      out.write("                                        class=\"purple-text text-darken-2 waves-effect waves-light\"\n");
      out.write("                                        href=\"#updateA\"><b>INFO 1</b></a></li>\n");
      out.write("                                <li class=\"tab col s6\"><a\n");
      out.write("                                        class=\"purple-text text-darken-2 waves-effect waves-light\"\n");
      out.write("                                        href=\"#updateB\"><b>INFO 2</b></a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                        <div id=\"updateA\" class=\"ftab col s12\" style=\"margin-top: 20px !important;\">\n");
      out.write("                            <div class=\"container\">\n");
      out.write("                                <div class=\"input-field col s12\">\n");
      out.write("                                    <input type=\"hidden\" name=\"intUpdatePackageID\" id=\"upPackageID\">\n");
      out.write("                                    <input type=\"text\" name=\"strUpdatePackageName\" id=\"upPackageName\"\n");
      out.write("                                           placeholder=\"Package Name\" required/>\n");
      out.write("                                    <label for=\"upPackageName\" class=\"active\"><b>Package Name</b><i\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"input-field col s12\">\n");
      out.write("                                            <textarea name=\"strUpdatePackageDesc\" class=\"materialize-textarea\"\n");
      out.write("                                                      placeholder=\"Description\"\n");
      out.write("                                                      id=\"upPackageDesc\" length=\"80\"\n");
      out.write("                                                      style=\"margin-top: -10px !important;\"></textarea>\n");
      out.write("                                    <label for=\"upPackageDesc\" class=\"active\"><b>Description</b></label>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"input-field col s12\">\n");
      out.write("                                    <select name=\"intUpdatePackageType\" id=\"upPackageType\" multiple required>\n");
      out.write("                                        <option value=\"default\" disabled>Choose...</option>\n");
      out.write("                                        <option value=\"1\">Event</option>\n");
      out.write("                                        <option value=\"2\">Home Service</option>\n");
      out.write("                                        <option value=\"3\">Walk-In</option>\n");
      out.write("                                    </select>\n");
      out.write("                                    <label for=\"upPackageType\"><b>Type</b><i\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div id=\"updateB\" class=\"ftab col s12\" style=\"margin-top: 15px !important;\">\n");
      out.write("                            <div class=\"col s4\">\n");
      out.write("                                <select name=\"\" id=\"upPackageFilter\">\n");
      out.write("                                    <option value=\"product\" selected>Product</option>\n");
      out.write("                                    <option value=\"service\">Service</option>\n");
      out.write("                                </select>\n");
      out.write("                                <label for=\"upPackageFilter\"><b>Select</b></label>\n");
      out.write("                            </div>\n");
      out.write("                            <nav class=\"right white z-depth-1\" style=\"width: 300px; margin-right: 20px;\">\n");
      out.write("                                <div class=\"nav-wrapper col s12\">\n");
      out.write("                                    <form>\n");
      out.write("                                        <div class=\"input-field\">\n");
      out.write("                                            <input id=\"uppackageSearch\" placeholder=\"Search\"\n");
      out.write("                                                   class=\"uppackageSearch grey-text text-darken-4\"\n");
      out.write("                                                   type=\"search\" style=\"border: none !important;\">\n");
      out.write("                                            <label for=\"uppackageSearch\"><i\n");
      out.write("                                                    class=\"material-icons grey-text text-darken-4\">search</i></label>\n");
      out.write("                                        </div>\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                            </nav>\n");
      out.write("                            <div class=\"col s12\">\n");
      out.write("                                <ul class=\"collapsible\" data-collapsible=\"accordion\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <div class=\"collapsible-header\"><i class=\"material-icons\">view_list</i>List\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"collapsible-body\"\n");
      out.write("                                             style=\"margin:0px 0px 0px 0px !important; padding: 0px 0px 0px 0px !important;\">\n");
      out.write("                                            <div class=\"tablewrapper\">\n");
      out.write("                                                <table id=\"uppackageProdtbl\"\n");
      out.write("                                                       class=\"uppackagetbl cell-border row-border display centered responsive-table highlight\"\n");
      out.write("                                                       cellspacing=\"0\" width=\"100%\"\n");
      out.write("                                                       style=\"border: 1px solid #bdbdbd; margin-top: -30px !important;\"\n");
      out.write("                                                       rowspan=\"5\">\n");
      out.write("                                                    <thead>\n");
      out.write("                                                    <tr>\n");
      out.write("                                                        <th class=\"dt-head-center no-sort\">Select</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Name</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Category</th>\n");
      out.write("                                                        <th class=\"dt-head-right\">Price</th>\n");
      out.write("                                                        <th align=\"dt-head-right\" class=\"no-sort\">Quantity</th>\n");
      out.write("                                                    </tr>\n");
      out.write("                                                    </thead>\n");
      out.write("                                                    <tfoot style=\"border: 1px solid #bdbdbd;\">\n");
      out.write("                                                    <tr>\n");
      out.write("                                                        <th class=\"dt-head-center no-sort\">ID</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Name</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Category</th>\n");
      out.write("                                                        <th class=\"dt-head-right\">Price</th>\n");
      out.write("                                                        <th align=\"dt-head-right\" class=\"no-sort\">Quantity</th>\n");
      out.write("                                                    </tr>\n");
      out.write("                                                    </tfoot>\n");
      out.write("\n");
      out.write("                                                    <tbody>\n");
      out.write("\n");
      out.write("                                                    </tbody>\n");
      out.write("                                                </table>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"tablewrapper\">\n");
      out.write("                                                <table id=\"uppackageServtbl\"\n");
      out.write("                                                       class=\"uppackagetbl cell-border row-border display centered responsive-table\"\n");
      out.write("                                                       cellspacing=\"0\" width=\"100%\"\n");
      out.write("                                                       style=\"border: 1px solid #bdbdbd; margin-top: -30px !important;\"\n");
      out.write("                                                       rowspan=\"5\">\n");
      out.write("                                                    <thead>\n");
      out.write("                                                    <tr>\n");
      out.write("                                                        <th class=\"dt-head-center no-sort\">Select</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Name</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Category</th>\n");
      out.write("                                                        <th class=\"dt-head-right\">Price</th>\n");
      out.write("                                                        <th align=\"dt-head-right\" class=\"no-sort\">Quantity</th>\n");
      out.write("                                                    </tr>\n");
      out.write("                                                    </thead>\n");
      out.write("                                                    <tfoot style=\"border: 1px solid #bdbdbd;\">\n");
      out.write("                                                    <tr>\n");
      out.write("                                                        <th class=\"dt-head-center no-sort\">ID</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Name</th>\n");
      out.write("                                                        <th class=\"dt-head-left\">Category</th>\n");
      out.write("                                                        <th class=\"dt-head-right\">Price</th>\n");
      out.write("                                                        <th align=\"dt-head-right\" class=\"no-sort\">Quantity</th>\n");
      out.write("                                                    </tr>\n");
      out.write("                                                    </tfoot>\n");
      out.write("\n");
      out.write("                                                    <tbody>\n");
      out.write("                                                    </tbody>\n");
      out.write("                                                </table>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col s9 z-depth-barts white\">\n");
      out.write("                                <h6 class=\"center\" style=\"padding-top: -2px !important;\"><b>Selected Items</b></h6>\n");
      out.write("                                <div class=\"col s12\" id=\"upPsList\"\n");
      out.write("                                     style=\"margin-top: -13px !important; margin-bottom: 5px !important;\"></div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col s3\">\n");
      out.write("                                <div class=\"input-field col s12\">\n");
      out.write("                                    <input type=\"text\" class=\"right-align grey-text text-darken-3\" disabled name=\"\"\n");
      out.write("                                           id=\"upPackTotal\" placeholder=\"Price\"/>\n");
      out.write("                                    <label for=\"upPackTotal\" class=\"active grey-text text-darken-3\"><b>Total</b></label>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"input-field col s12\" style=\"margin-top: 20px !important;\">\n");
      out.write("                                    <input type=\"text\" class=\"right-align prodPrice\" name=\"updatePackagePrice\" id=\"upPackPrice\"\n");
      out.write("                                           placeholder=\"Price\" required/>\n");
      out.write("                                    <label for=\"upPackPrice\" class=\"active\"><b>Price</b><i\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button class=\"red-text btn-flat transparent left\" disabled\n");
      out.write("                        style=\"margin:0px !important; padding:0px !important;\"><i\n");
      out.write("                        class=\"material-icons\">error_outline</i>&nbspRequired field\n");
      out.write("                </button>\n");
      out.write("                <a href=\"#!\"\n");
      out.write("                   class=\" modal-action modal-close waves-effect waves-purple transparent btn-flat\">CANCEL</a>\n");
      out.write("                <button class=\"waves-effect waves-light purple darken-3 white-text btn-flat\" type=\"submit\" onclick=\"updatePackage()\"\n");
      out.write("                        id=\"updatePackSubmitBtn\">SAVE\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
