/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-08-17 06:03:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class queries_002demployee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\" ng-controller=\"empQueryController as vm\">\r\n");
      out.write("    <div class=\"main z-depth-barts\" style=\"margin-left: 20px; margin-right: 20px;\">\r\n");
      out.write("        <div class=\"col s12\" style=\"margin-left: 20px; margin-right: 20px;\">\r\n");
      out.write("            <h3 class=\"grey-text center text-darken-1\">Query</h3>\r\n");
      out.write("            <!--<a class=\"btnshadow hoverable z-depth-1 waves-effect waves-light modal-trigger btn-flat purple darken-2 left white-text\"-->\r\n");
      out.write("               <!--href=\"#\" style=\"margin-top: 30px; margin-left: 15px;\"><i class=\"material-icons\">add</i></a>-->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"input-field col s3\">\r\n");
      out.write("                    <select ng-model=\"vm.filter.aiFilter\"\r\n");
      out.write("                            ng-options=\"position as position.strEmpValue for position in vm.aifilter\">\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-field col s3\">\r\n");
      out.write("                    <select>\r\n");
      out.write("                        <option ng-repeat=\"pos in vm.position\" value=\"{{pos}}\">{{pos}}</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>   \r\n");
      out.write("            </div>\r\n");
      out.write("            <nav class=\"right white hoverable  z-depth-1\" style=\"width: 300px; margin-right: 20px;\">\r\n");
      out.write("                <div class=\"nav-wrapper col s4\">\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <input id=\"querySearch\" placeholder=\"Search\" class=\"grey-text text-darken-4\" type=\"search\">\r\n");
      out.write("                            <label for=\"querySearch\"><i\r\n");
      out.write("                                    class=\"material-icons grey-text text-darken-4\">search</i></label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <table id=\"employeeQueryTable\" datatable=\"ng\" dt-options=\"vm.dtOptions\" dt-column-defs=\"vm.dtColumnDefs\"\r\n");
      out.write("                   class=\"row-border hoverable cell-border responsive z-depth-1\" rowspan=\"10\"\r\n");
      out.write("                   style=\"margin-top: -20px !important;\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th class=\"left-align\">Name</th>\r\n");
      out.write("                    <th class=\"left-align\">Position</th>\r\n");
      out.write("                    <th class=\"right-align\">Contact</th>\r\n");
      out.write("                    <th class=\"left-align\">Email</th>\r\n");
      out.write("                    <th class=\"left-align\">Address</th>\r\n");
      out.write("                    <th class=\"left-align\">Status</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tfoot>\r\n");
      out.write("                <tr style=\"border: 1px solid #bdbdbd;\">\r\n");
      out.write("                    <th class=\"left-align\">Name</th>\r\n");
      out.write("                    <th class=\"left-align\">Position</th>\r\n");
      out.write("                    <th class=\"right-align\">Contact</th>\r\n");
      out.write("                    <th class=\"left-align\">Email</th>\r\n");
      out.write("                    <th class=\"left-align\">Address</th>\r\n");
      out.write("                    <th class=\"left-align\">Status</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </tfoot>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                <tr ng-repeat=\"employee in vm.employeeList | filter: AIFilter\">\r\n");
      out.write("                    <td class=\"left-align\" style=\"width: 300px !important;\"\r\n");
      out.write("                        title=\"{{ employee.strEmpFirstName + ' ' + employee.strEmpMiddleName + ' ' + employee.strEmpLastName }}\">\r\n");
      out.write("                        {{ employee.strEmpFirstName + ' ' + employee.strEmpMiddleName + ' ' + employee.strEmpLastName }}\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"left-align\" style=\"width: 300px !important;\">\r\n");
      out.write("                        {{ employee.jobQualification.strJobDesc}},\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"right-align\">{{ employee.strEmpContactNo }}</td>\r\n");
      out.write("                    <td class=\"left-align\" style=\"width: 100px !important;\">{{ employee.strEmpEmail }}</td>\r\n");
      out.write("                    <td class=\"left-align\">{{ employee.strEmpAddress }}</td>\r\n");
      out.write("                    <td class=\"left-align\"\r\n");
      out.write("                        ng-if=\"strEmpStatus == 'I'\">\r\n");
      out.write("                        INACTIVE\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"left-align\"\r\n");
      out.write("                        ng-if=\"strEmpStatus != 'I'\">\r\n");
      out.write("                        ACTIVE\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"paymentModal\" class=\"modal modal-fixed-footer\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <h4 class=\"grey-text center text-darken-1\">Payment for {{vm.paymentDetails.strName}}</h4>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"input-field col s6\">\r\n");
      out.write("                        <input type=\"hidden\" ng-model=\"vm.paymentDetails.index\">\r\n");
      out.write("                        <input type=\"text\" id=\"paymentDetails.name\" placeholder=\"Customer Name\" readonly\r\n");
      out.write("                               ng-model=\"vm.paymentDetails.strName\">\r\n");
      out.write("                        <label for=\"paymentDetails.name\" class=\"active\"><b>Customer Name</b></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-field col s6\">\r\n");
      out.write("                        <input type=\"text\" id=\"paymentDetails.date\" placeholder=\"Payment Date\" readonly\r\n");
      out.write("                               ng-model=\"vm.paymentDetails.paymentCreated\"/>\r\n");
      out.write("                        <label for=\"paymentDetails.date\" class=\"active\"><b>Payment Date</b></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-field col s6\">\r\n");
      out.write("                        <input type=\"text\" id=\"paymentDetails.totalBalance\" class=\"right-align\" placeholder=\"Total Balance\" readonly\r\n");
      out.write("                               ng-model=\"vm.paymentDetails.totalBalance\"/>\r\n");
      out.write("                        <label for=\"paymentDetails.totalBalance\" class=\"active\"><b>Total Balance</b></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-field col s6\">\r\n");
      out.write("                        <input type=\"text\" id=\"paymentDetails.remainingBalance\" class=\"right-align\" placeholder=\"Total Balance\" readonly\r\n");
      out.write("                               ng-model=\"vm.paymentDetails.remainingBalance\"/>\r\n");
      out.write("                        <label for=\"paymentDetails.remainingBalance\" class=\"active\"><b>Remaining Balance</b></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-field col s6\">\r\n");
      out.write("                        <select id=\"paymentDetails.type\"\r\n");
      out.write("                                ng-model=\"vm.paymentDetails.paymentType\">\r\n");
      out.write("                            <option value=\"{{vm.paymentType[0].option1}}\" selected>Full Payment</option>\r\n");
      out.write("                            <option ng-if=\"vm.paymentDetails.type == 'reservation'\"\r\n");
      out.write("                                    value=\"{{vm.paymentType[0].option2}}\">Down Payment</option>\r\n");
      out.write("                            <option ng-if=\"vm.paymentDetails.type=='reservation' || vm.paymentDetails.type=='walkin'\"\r\n");
      out.write("                                    value=\"{{vm.paymentType[0].option2}}\">Complementary Payment</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-field col s6\">\r\n");
      out.write("                        <input type=\"text\" id=\"paymentDetails.paymentAmount\" class=\"right-align\" placeholder=\"Payment Amount\" required\r\n");
      out.write("                               ng-model=\"vm.paymentDetails.paymentAmount\"\r\n");
      out.write("                               format=\"number\"/>\r\n");
      out.write("                        <label for=\"paymentDetails.paymentAmount\" class=\"active\"><b>Payment Amount</b>\r\n");
      out.write("                            <i class=\"material-icons tiny red-text\">error_outline</i></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("            <button class=\"red-text btn-flat transparent left\" disabled\r\n");
      out.write("                    style=\"margin:0px !important; padding:0px !important;\"><i\r\n");
      out.write("                    class=\"material-icons\">error_outline</i>&nbspRequired field\r\n");
      out.write("            </button>\r\n");
      out.write("            <button type=\"submit\" value=\"Submit\" id=\"paymentDetails.submit\"\r\n");
      out.write("                    class=\"waves-effect waves-light white-text btn-flat purple\"\r\n");
      out.write("                    style=\"margin-left:3px; margin-right:3px;\"\r\n");
      out.write("                    ng-click=\"vm.paymentSubmit(vm.paymentDetails)\">CREATE\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
