/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-08-17 11:39:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gss.model.Discount;

public final class transactions_002dreservation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\" ng-controller= \"reservationTable as vm\">\r\n");
      out.write("    <div class=\"main z-depth-barts\" style=\"margin-left: 20px; margin-right: 20px;\">\r\n");
      out.write("        <div class=\"col s12\" style=\"margin-left: 20px; margin-right: 20px;\">\r\n");
      out.write("            <h3 class=\"grey-text text-darken-1\">Reservation</h3>\r\n");
      out.write("            <a class=\"crReservation z-depth-1 hoverable waves-effect waves-light modal-trigger btn purple darken-2 left white-text\"\r\n");
      out.write("               href=\"#createReservationModal\" style=\"margin-top: 30px; margin-left: 15px;\"><i\r\n");
      out.write("                    class=\"material-icons\">add</i></a>\r\n");
      out.write("            <a class=\"z-depth-1 hoverable waves-effect waves-light modal-trigger btn purple darken-2 left white-text\"\r\n");
      out.write("               href=\"#reservationModal\" style=\"margin-top: 30px; margin-left: 15px;\"><i class=\"material-icons\">archive</i></a>\r\n");
      out.write("            <nav class=\"right white hoverable  z-depth-1\" style=\"width: 300px; margin-right: 20px;\">\r\n");
      out.write("                <div class=\"nav-wrapper col s4\">\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <input id=\"reservationSearch\" placeholder=\"Search\" class=\"grey-text text-darken-4\"\r\n");
      out.write("                                   type=\"search\" required>\r\n");
      out.write("                            <label for=\"reservationSearch\"><i\r\n");
      out.write("                                    class=\"material-icons grey-text text-darken-4\">search</i></label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <table id=\"reservationtbl\"\r\n");
      out.write("                   class=\"hoverable z-depth-1 cell-border row-border display centered responsive-table highlight\"\r\n");
      out.write("                   datatable=\"ng\" dt-options=\"vm.dtOptions\" dt-column-defs=\"vm.dtColumnDefs\"\r\n");
      out.write("                   style=\"border: 1px solid #bdbdbd; padding: 10px; margin-top: -30px !important;\" rowspan=\"10\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th class=\"dt-head-left\">Customer Name</th>\r\n");
      out.write("                    <th class=\"dt-head-left\">Customer Type</th>\r\n");
      out.write("                    <th class=\"dt-head-left\">Reservation Type</th>\r\n");
      out.write("                    <th class=\"dt-head-left no-sort\">Venue</th>\r\n");
      out.write("                    <th class=\"dt-head-right\">Reservation Date</th>\r\n");
      out.write("                    <th class=\"dt-head-left\">Status</th>\r\n");
      out.write("                    <th align=\"dt-head-center\" class=\"no-sort\">Action</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                \t<tr ng-repeat=\"customer in vm.customerList\">\r\n");
      out.write("\t                \t<td class=\"dt-head-left\">{{customer.customer.strName}}</td>\r\n");
      out.write("\t                    <td class=\"dt-head-left\">{{customer.intReservationType}}</td>\r\n");
      out.write("\t                    <td class=\"dt-head-left\">{{customer.intReservationType}}</td>\r\n");
      out.write("\t                    <td class=\"dt-head-left no-sort\">{{customer.strVenue}}</td>\r\n");
      out.write("\t                    <td class=\"dt-head-right\">{{customer.datFrom}}</td>\r\n");
      out.write("\t                    <td class=\"dt-head-left\">REQUEST</td>\r\n");
      out.write("\t                    <td align=\"dt-head-center\" class=\"no-sort\"><center><button class='waves-effect waves-light modal-trigger btn-flat transparent black-text'\r\n");
      out.write("\t                                title='Accept' onclick='acceptOrder(this.value)' id='acc' style='padding: 0px;'>\r\n");
      out.write("\t                                <i class='material-icons light-green-text text-darken-3'>check_circle</i></button><button class='prodsalesdeacbtn waves-effect waves-light btn-flat transparent\r\n");
      out.write("\t                                red-text text-accent-4' title='Decline' onclick='declineOrder(this.value)'>\r\n");
      out.write("\t                                <i class='material-icons'>cancel</i></button></center></td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("                <tfoot style=\"border: 1px solid #bdbdbd;\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th class=\"dt-head-left\">Customer Name</th>\r\n");
      out.write("                    <th class=\"dt-head-left\">Customer Type</th>\r\n");
      out.write("                    <th class=\"dt-head-left\">Reservation Type</th>\r\n");
      out.write("                    <th class=\"dt-head-left no-sort\">Venue</th>\r\n");
      out.write("                    <th class=\"dt-head-right\">Date of event</th>\r\n");
      out.write("                    <th class=\"dt-head-left\">Status</th>\r\n");
      out.write("                    <th align=\"dt-head-center\" class=\"no-sort\">Action</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </tfoot>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal Structure -->\r\n");
      out.write("     <div id=\"quanty\" class=\"modal\">\r\n");
      out.write("       <div class=\"modal-content\">\r\n");
      out.write("         <h4>Modal Header</h4>\r\n");
      out.write("         <p>A bunch of text</p>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"modal-footer\">\r\n");
      out.write("         <a href=\"#!\" class=\" modal-action modal-close waves-effect waves-green btn-flat\">Agree</a>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Modal Structure -->\r\n");
      out.write("    <div id=\"createReservationModal\" class=\"modal modal-fixed-footer\"\r\n");
      out.write("    style=\"width: 90% !important; height: 90% !important; max-height: 100% !important; margin-top: -40px;\">\r\n");
      out.write("        <form class=\"col s12\" id=\"createReservationForm\" method=\"post\" ng-submit=\"vm.saveReservation()\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <!-- <div class=\"container\"> -->\r\n");
      out.write("                <div class=\"wrapper\">\r\n");
      out.write("                    <h4 class=\"center grey-text text-darken-1\">Create Reservation<a id=\"btnCrExtraExit\" type=\"reset\"\r\n");
      out.write("                                                                                 value=\"Reset\"\r\n");
      out.write("                                                                                 class=\"modal-action modal-close\"><i\r\n");
      out.write("                            class=\"small material-icons right grey-text text-darken-4\">close</i></a></h4>\r\n");
      out.write("                    <div class=\"progress\">\r\n");
      out.write("                        <div class=\"determinate center active purple darken-4 white-text\" role=\"progressbar\"\r\n");
      out.write("                             aria-valuemin=\"0\"\r\n");
      out.write("                             aria-valuemax=\"100\" style=\"color: white;\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"reservationerrorcontainer card red center input-field col s12 white-text z-depth-barts\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stepreservation well\" style=\"margin-top: -5px;\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <h5><b>Customer Details</b></h5>\r\n");
      out.write("                            <div class=\"input-field col s12\">\r\n");
      out.write("                                <input type=\"text\" class=\"validate\" id=\"crRCustName\"\r\n");
      out.write("                                       ng-model=\"vm.details.name\" placeholder=\"Customer Name\"/>\r\n");
      out.write("                                <label for=\"crRCustName\" class=\"active\"><b>Customer Name</b><i\r\n");
      out.write("                                        class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s12\" style=\"margin-top: 15px;\">\r\n");
      out.write("                                <input type=\"text\" id=\"crRAddress\" ng-model=\"vm.details.address\"  placeholder=\"Address\"/>\r\n");
      out.write("                                <label for=\"crRAddress\" class=\"active\"><b>Address</b><i\r\n");
      out.write("                                        class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\">\r\n");
      out.write("                                <input type=\"text\" id=\"crRContact\" ng-model=\"vm.details.contact\"  placeholder=\"contact\"/>\r\n");
      out.write("                                <label for=\"crRContact\" class=\"active\"><b>Contact</b><i\r\n");
      out.write("                                        class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\" style=\"margin-top: 15px;\">\r\n");
      out.write("                                <input type=\"email\" ng-model=\"vm.details.email\"  id=\"crREmail\" placeholder=\"Email\"/>\r\n");
      out.write("                                <label for=\"crREmail\" class=\"active\"><b>Email</b><i\r\n");
      out.write("                                        class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\">\r\n");
      out.write("                                <label style=\"margin-top: -25px;\"><b>Customer Type</b></label>\r\n");
      out.write("                                <input type=\"radio\" name=\"ctype\" id=\"crRCustType1\">\r\n");
      out.write("                                <label for=\"crRCustType1\">Individual</label>\r\n");
      out.write("                                <input type=\"radio\" name=\"ctype\" id=\"crRCustType2\">\r\n");
      out.write("                                <label for=\"crRCustType2\">Company</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\">\r\n");
      out.write("                                <input type=\"text\" class=\"validate\"\r\n");
      out.write("                                       id=\"crRCompanyName\" ng-model=\"vm.details.company\" \r\n");
      out.write("                                       placeholder=\"Company Name\">\r\n");
      out.write("                                <label for=\"crRCompanyName\"><b>Company Name</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stepreservation well\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <h5><b>Reservation Details</b></h5>\r\n");
      out.write("                            <div class=\"input-field col s12\">\r\n");
      out.write("                                <input type=\"text\" class=\"validate\" id=\"crREventVenue\"\r\n");
      out.write("                                      ng-model=\"vm.details.venue\"  placeholder=\"Event Venue\"/>\r\n");
      out.write("                                <label for=\"crREventVenue\" class=\"active\"><b>Event Venue</b><i\r\n");
      out.write("                                        class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\">\r\n");
      out.write("                                <input type=\"date\" ng-model=\"vm.details.dtFrom\" class=\"datepicker\"\r\n");
      out.write("                                       id=\"abc\" placeholder=\"Ex: 01/01/01\"\r\n");
      out.write("                                       required/>\r\n");
      out.write("                                <label for=\"abc\"><b>Date From</b><i\r\n");
      out.write("                                        class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\">\r\n");
      out.write("                                <input type=\"date\" ng-model=\"vm.details.dtTo\" class=\"datepicker\"\r\n");
      out.write("                                       placeholder=\"Ex: 01/01/01\"\r\n");
      out.write("                                       required/> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s12\">\r\n");
      out.write("                                <label for=\"timepicker\">Time</label>\r\n");
      out.write("                                <input id=\"timepicker\" class=\"timepicker\" type=\"time\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\" style=\"margin-top: 15px;\">\r\n");
      out.write("                                <input type=\"text\" ng-model=\"vm.details.tmTo\"  id=\"crRToTime\" placeholder=\"crRToTime\"/>\r\n");
      out.write("                                <label for=\"crRToTime\" class=\"active\"><b>To (Time)</b><i\r\n");
      out.write("                                        class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\">\r\n");
      out.write("                                <input type=\"text\" ng-model=\"vm.details.headCount\"  id=\"crRHeadCount\" placeholder=\"Headcount\"/>\r\n");
      out.write("                                <label for=\"crRHeadCount\"><b>Head Count</b><i\r\n");
      out.write("                                        class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stepreservation well\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col s4\">\r\n");
      out.write("                                <select name=\"\" id=\"discountFilter\" ng-model=\"vm.selected\">\r\n");
      out.write("                                    <option value=\"product\" selected>Product</option>\r\n");
      out.write("                                    <option value=\"service\">Service</option>\r\n");
      out.write("                                    <option value=\"package\">Package</option>\r\n");
      out.write("                                    <option value=\"promo\">Promo</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                                <label for=\"discountFilter\"><b>Select</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <nav class=\"right white z-depth-1\" style=\"width: 300px; margin-right: 20px;\">\r\n");
      out.write("                                <div class=\"nav-wrapper col s12\">\r\n");
      out.write("                                    <form>\r\n");
      out.write("                                        <div class=\"input-field\">\r\n");
      out.write("                                            <input id=\"crDiscountSearch\" placeholder=\"Search\"\r\n");
      out.write("                                                   class=\"grey-text text-darken-4\"\r\n");
      out.write("                                                   type=\"search\" style=\"border: none !important;\">\r\n");
      out.write("                                            <label for=\"crDiscountSearch\"><i\r\n");
      out.write("                                                    class=\"material-icons grey-text text-darken-4\">search</i></label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </nav>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row col s12\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("       \r\n");
      out.write("                 <div ng-show=\"vm.selected == 'product'\">\r\n");
      out.write("                    <div class=\"row \">\r\n");
      out.write("                        <div class=\"col s2\" ng-repeat=\"product in vm.productList\">\r\n");
      out.write("                            <div class=\"card small\">\r\n");
      out.write("                                <div class=\"card-image waves-effect waves-block waves-light\">\r\n");
      out.write("                                    <img class=\"activator\" ng-src=\"{{product.strPhotoPath}}\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <a class=\"activator grey-text text-darken-4 light btn btn-small center\" style=\"margin-top: -10px;\"><i class=\"material-icons right white-text\">add_shopping_cart</i></a>\r\n");
      out.write("                                    <h5 style='font-size: 12px; line-height: 10px !important;'><b>{{product.strProductName}}</b>\r\n");
      out.write("                                        <p>{{product.dblProductPrice | currency:\"P\"}}</p></h5>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-reveal\">\r\n");
      out.write("\r\n");
      out.write("                                    <span class=\"card-title grey-text text-darken-4\"><i\r\n");
      out.write("                                            class=\"material-icons right\">close</i></span>\r\n");
      out.write("                                    <h4 style='font-size: 12px; line-height: 15px !important;'>\r\n");
      out.write("                                        <b>{{product.strProductName}}</b><br/>\r\n");
      out.write("                                        <span class=\"grey-text text-darken-4\">{{product.dblProductPrice | currency:\"Php \"}}</span>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <div class=\"input-field col s12\">\r\n");
      out.write("                                        <input type=\"number\" id=\"crPSQty{{product.intProductID}}\" ng-model=\"vm.quantity\"/>\r\n");
      out.write("                                        <label for=\"crPSQty{{product.intProductID}}\"><b>Quantity</b></label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h6 class=\"grey-text text-darken-4\">{{product.dblProductPrice * vm.quantity | currency:\r\n");
      out.write("                                        \"Php \"}}</h6>\r\n");
      out.write("\r\n");
      out.write("                                    <a class=\"waves-effect waves-light btn\" ng-click=\"vm.addToCart($index, vm.selected); vm.sumTotal()\">\r\n");
      out.write("                                        <i class=\"material-icons left\" style=\"padding: 0px !important; margin: 0px !important;\">\r\n");
      out.write("                                            shopping_basket</i>BUY NOW!\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("\r\n");
      out.write("                <div ng-show=\"vm.selected == 'service'\">\r\n");
      out.write("                    <div class=\"row \">\r\n");
      out.write("                        <div class=\"col s2\" ng-repeat=\"service in vm.serviceList\">\r\n");
      out.write("                            <div class=\"card small\">\r\n");
      out.write("                                <div class=\"card-image waves-effect waves-block waves-light\">\r\n");
      out.write("                                    <img class=\"activator\" ng-src=\"{{service.strPhotoPath}}\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-content\">\r\n");
      out.write("                                    <a class=\"activator grey-text text-darken-4 light btn btn-small center\" style=\"margin-top: -10px;\"><i class=\"material-icons right white-text\">add_shopping_cart</i></a>\r\n");
      out.write("                                    <h5 style='font-size: 12px; line-height: 10px !important;'><b>{{service.strServiceName}}</b>\r\n");
      out.write("                                        <p>{{service.dblServicePrice | currency:\"P\"}}</p></h5>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"card-reveal\">\r\n");
      out.write("\r\n");
      out.write("                                    <span class=\"card-title grey-text text-darken-4\"><i\r\n");
      out.write("                                            class=\"material-icons right\">close</i></span>\r\n");
      out.write("                                    <h4 style='font-size: 12px; line-height: 15px !important;'>\r\n");
      out.write("                                        <b>{{service.strServiceName}}</b><br/>\r\n");
      out.write("                                        <span class=\"grey-text text-darken-4\">{{service.dblServicePrice | currency:\"Php \"}}</span>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <div class=\"input-field col s12\">\r\n");
      out.write("                                        <input type=\"number\" id=\"crPSQty{{product.intProductID}}\" ng-model=\"vm.quantity\"/>\r\n");
      out.write("                                        <label for=\"crPSQty{{product.intProductID}}\"><b>Quantity</b></label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h6 class=\"grey-text text-darken-4\">{{service.dblServicePrice * vm.quantity | currency:\r\n");
      out.write("                                        \"Php \"}}</h6>\r\n");
      out.write("\r\n");
      out.write("                                     <a class=\"waves-effect waves-light btn\" ng-click=\"vm.addToCart($index, vm.selected); vm.sumTotal()\">\r\n");
      out.write("                                        <i class=\"material-icons left\" style=\"padding: 0px !important; margin: 0px !important;\">\r\n");
      out.write("                                            shopping_basket</i>BUY NOW!\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div ng-show=\"vm.selected == 'package'\">\r\n");
      out.write("                   <div class=\"row \">\r\n");
      out.write("                       <div class=\"col s2\" ng-repeat=\"package in vm.packageList\">\r\n");
      out.write("                           <div class=\"card small\">\r\n");
      out.write("                               <div class=\"card-image waves-effect waves-block waves-light\">\r\n");
      out.write("                                   <img class=\"activator\" ng-src=\"{{service.strPhotoPath}}\">\r\n");
      out.write("                               </div>\r\n");
      out.write("                               <div class=\"card-content\">\r\n");
      out.write("                                   <a class=\"activator grey-text text-darken-4 light btn btn-small center\" style=\"margin-top: -10px;\"><i class=\"material-icons right white-text\">add_shopping_cart</i></a>\r\n");
      out.write("                                   <h5 style='font-size: 12px; line-height: 10px !important;'><b>{{package.strPackageName}}</b>\r\n");
      out.write("                                       <p>{{package.dblPackagePrice | currency:\"P\"}}</p></h5>\r\n");
      out.write("                               </div>\r\n");
      out.write("                               <div class=\"card-reveal\">\r\n");
      out.write("\r\n");
      out.write("                                   <span class=\"card-title grey-text text-darken-4\"><i\r\n");
      out.write("                                           class=\"material-icons right\">close</i></span>\r\n");
      out.write("                                   <h4 style='font-size: 12px; line-height: 15px !important;'>\r\n");
      out.write("                                       <b>{{package.strPackageName}}</b><br/>\r\n");
      out.write("                                       <span class=\"grey-text text-darken-4\">{{package.dblPackagePrice | currency:\"Php \"}}</span>\r\n");
      out.write("                                   </h4>\r\n");
      out.write("                                   <div class=\"input-field col s12\">\r\n");
      out.write("                                       <input type=\"number\" id=\"crPSQty{{product.intProductID}}\" ng-model=\"vm.quantity\"/>\r\n");
      out.write("                                       <label for=\"crPSQty{{product.intProductID}}\"><b>Quantity</b></label>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   <h6 class=\"grey-text text-darken-4\">{{package.dblPackagePrice * vm.quantity | currency: \"Php \"}}</h6>\r\n");
      out.write("\r\n");
      out.write("                                   <a class=\"waves-effect waves-light btn\" ng-click=\"vm.addToCart($index, vm.selected); vm.sumTotal()\">\r\n");
      out.write("                                        <i class=\"material-icons left\" style=\"padding: 0px !important; margin: 0px !important;\">\r\n");
      out.write("                                            shopping_basket</i>BUY NOW!\r\n");
      out.write("                                    </a>\r\n");
      out.write("                               </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div ng-show=\"vm.selected == 'promo'\">\r\n");
      out.write("                    <div class=\"row \">\r\n");
      out.write("                       <div class=\"col s2\" ng-repeat=\"promo in vm.promoList\">\r\n");
      out.write("                           <div class=\"card small\">\r\n");
      out.write("                               <div class=\"card-image waves-effect waves-block waves-light\">\r\n");
      out.write("                                   <img class=\"activator\" ng-src=\"{{service.strPhotoPath}}\">\r\n");
      out.write("                               </div>\r\n");
      out.write("                               <div class=\"card-content\">\r\n");
      out.write("                                   <a class=\"activator grey-text text-darken-4 light btn btn-small center\" style=\"margin-top: -10px;\"><i class=\"material-icons right white-text\">add_shopping_cart</i></a>\r\n");
      out.write("                                   <h5 style='font-size: 12px; line-height: 10px !important;'><b>{{promo.strPromoName}}</b>\r\n");
      out.write("                                       <p>{{promo.dblPromoPrice | currency:\"P\"}}</p></h5>\r\n");
      out.write("                               </div>\r\n");
      out.write("                               <div class=\"card-reveal\">\r\n");
      out.write("\r\n");
      out.write("                                   <span class=\"card-title grey-text text-darken-4\"><i\r\n");
      out.write("                                           class=\"material-icons right\">close</i></span>\r\n");
      out.write("                                   <h4 style='font-size: 12px; line-height: 15px !important;'>\r\n");
      out.write("                                       <b>{{promo.strPromoName}}</b><br/>\r\n");
      out.write("                                       <span class=\"grey-text text-darken-4\">{{promo.dblPromoPrice | currency:\"Php \"}}</span>\r\n");
      out.write("                                   </h4>\r\n");
      out.write("                                   <div class=\"input-field col s12\">\r\n");
      out.write("                                       <input type=\"number\" id=\"crPSQty{{product.intProductID}}\" ng-model=\"vm.quantity\"/>\r\n");
      out.write("                                       <label for=\"crPSQty{{product.intProductID}}\"><b>Quantity</b></label>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   <h6 class=\"grey-text text-darken-4\">{{promo.dblPromoPrice * vm.quantity | currency:\r\n");
      out.write("                                       \"Php \"}}</h6>\r\n");
      out.write("\r\n");
      out.write("                                   <a class=\"waves-effect waves-light btn\" ng-click=\"vm.addToCart($index, vm.selected); vm.sumTotal()\">\r\n");
      out.write("                                        <i class=\"material-icons left\" style=\"padding: 0px !important; margin: 0px !important;\">\r\n");
      out.write("                                            shopping_basket</i>BUY NOW!\r\n");
      out.write("                                    </a>\r\n");
      out.write("                               </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                                        \r\n");
      out.write("               <div class=\"col s12 z-depth-barts white\" id=\"\">\r\n");
      out.write("                    <h6 class=\"center\" style=\"padding-top: -2px !important;\"><b>Selected Items</b></h6>\r\n");
      out.write("                    <div class=\"col s12\" id=\"pslist\" style=\"margin-top: -13px !important; margin-bottom: 5px !important;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col s4\" style=\"margin-top: 10px;\">\r\n");
      out.write("                    <div class=\"input-field col s12\">\r\n");
      out.write("                        <select multiple ng-model=\"vm.extraCharge\" id=\"crROtherCharge\" ng-options=\"charge.strECName for charge in vm.extraChargeList\"></select>\r\n");
      out.write("                            \r\n");
      out.write("                        <label for=\"crROtherCharge\"><b>Other Charges</b></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col s4\" style=\"margin-top: 10px;\">\r\n");
      out.write("                    <div class=\"input-field col s12\">\r\n");
      out.write("                       <select multiple ng-model=\"vm.selDiscounts\" id=\"crRDiscount\" ng-options=\"discount.strDiscountName for discount in vm.discountList\"></select>\r\n");
      out.write("                        <label for=\"crRDiscount\"><b>Discounts</b></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col s4 z-depth-barts white\" style=\"margin-top: 10px;\">\r\n");
      out.write("                    <div class=\"col s12\">\r\n");
      out.write("                        <div class=\"input-field col s12\">\r\n");
      out.write("                            <h5 class=\"green-text\">Total: {{vm.sum | currency: \"Php\"}}</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>  \r\n");
      out.write("                 <div class=\"col s8\" style=\"margin-top: 10px;\">\r\n");
      out.write("                    <div class=\"input-field col s12\">\r\n");
      out.write("                       <select multiple ng-model=\"vm.selEmployees\" id=\"cREmp\" ng-options=\"employee.strEmpFirstName for employee in vm.employeeList\"></select>\r\n");
      out.write("                        <label for=\"cREmp\"><b>Employees</b></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stepreservation well\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <h3 class=\"center\"><b>Summary</b></h3>\r\n");
      out.write("                            <h5><b>Customer Details</b></h5>\r\n");
      out.write("                            <div class=\"input-field col s12\" id=\"crRSumCustName\">\r\n");
      out.write("                                <input type=\"text\" class=\"validate\"/>\r\n");
      out.write("                                <label for=\"crRSumCustName\" class=><b>Customer Name</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s12\" style=\"margin-top: 15px;\">\r\n");
      out.write("                                <input type=\"text\" id=\"crRSumAddress\" name=\"\" placeholder=\"\"/>\r\n");
      out.write("                                <label for=\"crRSumAddress\"><b>Address</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\">\r\n");
      out.write("                                <input type=\"text\" id=\"crRSumContact\" name=\"\" />\r\n");
      out.write("                                <label for=\"crRSumContact\"><b>Contact</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\" style=\"margin-top: 15px;\">\r\n");
      out.write("                                <input type=\"email\" name=\"\" id=\"crRSumEmail\"/>\r\n");
      out.write("                                <label for=\"crRSumEmail\" class=\"active\"><b>Email</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\">\r\n");
      out.write("                                <input type=\"text\" name=\"\" id=\"crRSumCustType\"/>\r\n");
      out.write("                                <label for=\"crRSumCustType\"><b>Customer Type</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <h5><b>Reservation Details</b></h5>\r\n");
      out.write("                            <div class=\"input-field col s12\">\r\n");
      out.write("                                <input type=\"text\" class=\"validate\" id=\"crRSumEventVenue\"\r\n");
      out.write("                                       name=\"\"/>\r\n");
      out.write("                                <label for=\"crRSumEventVenue\"><b>Event Venue</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\" style=\"margin-top: 15px;\">\r\n");
      out.write("                                <input type=\"text\" id=\"crRSumFromDate\" name=\"\"/>\r\n");
      out.write("                                <label for=\"crRSumFromDate\"><b>From (Date)</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\" style=\"margin-top: 15px;\">\r\n");
      out.write("                                <input type=\"text\" id=\"crRSumToDate\" name=\"\"/>\r\n");
      out.write("                                <label for=\"crRSumToDate\" class=\"active\"><b>To (Date)</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s12\">\r\n");
      out.write("                                <label for=\"timepicker\">Time</label>\r\n");
      out.write("                                <input id=\"timepicker\" class=\"timepicker\" type=\"time\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-field col s6\" style=\"margin-top: 15px;\">\r\n");
      out.write("                                <input type=\"text\" name=\"\" id=\"crRSumToTime\" />\r\n");
      out.write("                                <label for=\"crRSumToTime\" class=\"active\"><b>To (Time)</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"input-field col s6\">\r\n");
      out.write("                                <input type=\"text\" name=\"\" id=\"crRSumHeadCount\" />\r\n");
      out.write("                                <label for=\"crRSumHeadCount\"><b>Head Count</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <h5><b>Selected Items</b></h5>\r\n");
      out.write("                            <div class=\"col s12\">\r\n");
      out.write("                                <h6 class=\"grey-text text-darken-3\"><b>Services</b></h6>\r\n");
      out.write("                                <table>\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th class=\"left-align grey-text text-darken-3\">Service Name</th>\r\n");
      out.write("                                        <th class=\"right-align grey-text text-darken-3\">Price</th>\r\n");
      out.write("                                        <th class=\"right-align grey-text text-darken-3\">Quantity</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col s12\">\r\n");
      out.write("                                <h6 class=\"grey-text text-darken-3\"><b>Products</b></h6>\r\n");
      out.write("                                <table>\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th class=\"left-align grey-text text-darken-3\">Product Name</th>\r\n");
      out.write("                                        <th class=\"right-align grey-text text-darken-3\">Price</th>\r\n");
      out.write("                                        <th class=\"right-align grey-text text-darken-3\">Quantity</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <h5><b>Other Charges</b></h5>\r\n");
      out.write("                            <div class=\"col s12\">\r\n");
      out.write("                                <table>\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th class=\"grey-text text-darken-3\">Charge Name</th>\r\n");
      out.write("                                        <th class=\"grey-text text-darken-3\">Price</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <h5 class=\"grey-text text-darken-3\"><b>Discounts</b></h5>\r\n");
      out.write("                            <div class=\"col s12\">\r\n");
      out.write("                                <table>\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th class=\"grey-text text-darken-3\">Discount Name</th>\r\n");
      out.write("                                        <th class=\"grey-text text-darken-3\">Price</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col s12\">\r\n");
      out.write("                                <table>\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th class=\"left-align\"><b>Payment Type</b></th>\r\n");
      out.write("                                        <th class=\"right-align\"><b>Total Price</b></th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                </table>\r\n");
      out.write("                                <p class=\"red-text\">\r\n");
      out.write("                                    Note: First payment should be settled right after the reservation is created.\r\n");
      out.write("                                          Second payment will be collected on the day of the event after the program.\r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                                <p>\r\n");
      out.write("                                \tBy clicking create, you AGREE to our terms and agreements stated in the\r\n");
      out.write("                                    <a class=\"blue-text\" href=\"\">Reservation Contract</a>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button class=\"red-text btn-flat transparent left\" disabled\r\n");
      out.write("                        style=\"margin:0px !important; padding:0px !important;\"><i\r\n");
      out.write("                        class=\"material-icons\">error_outline</i>&nbspRequired field\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"button\" id=\"nextbtn\"\r\n");
      out.write("                        class=\"actionreserve nextformreserve waves-effect waves-light white-text btn-flat purple\"\r\n");
      out.write("                        style=\"margin-left: 3px; margin-right:3px;\">NEXT\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"submit\" value=\"submit\" id=\"createReservationSubmitForm\"\r\n");
      out.write("                        class=\" waves-effect waves-light white-text btn-flat purple\"\r\n");
      out.write("                        style=\"margin-left:3px; margin-right:3px;\"\r\n");
      out.write("                        ng-click=\"vm.saveReservation()\">CREATE\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"button\" id=\"backbtn\"\r\n");
      out.write("                        class=\"actionreserve backformreserve waves-effect waves-purple transparent btn-flat\"\r\n");
      out.write("                        style=\"margin-left: 3px;margin-right:3px;\">BACK\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
