/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-08-17 09:26:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class transactions_002dwalkin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"wrapper\" ng-controller=\"walkinCtrl as vm\">\n");
      out.write("    <div class=\"main z-depth-barts\" style=\"margin-left: 20px; margin-right: 20px;\">\n");
      out.write("        <div class=\"col s12\" style=\"margin-left: 20px; margin-right: 20px;\">\n");
      out.write("            <h3 class=\"grey-text text-darken-1\">Walk-In</h3>\n");
      out.write("            <a class=\"crWalkin z-depth-1 hoverable waves-effect waves-light modal-trigger btn purple darken-2 left white-text\"\n");
      out.write("               href=\"#createWalkinModal\" style=\"margin-top: 30px; margin-left: 15px;\"><i\n");
      out.write("                    class=\"material-icons\">add</i></a>\n");
      out.write("            <a class=\"z-depth-1 hoverable waves-effect waves-light modal-trigger btn purple darken-2 left white-text\"\n");
      out.write("               href=\"#walkinModal\" style=\"margin-top: 30px; margin-left: 15px;\"><i\n");
      out.write("                    class=\"material-icons\">archive</i></a>\n");
      out.write("            <nav class=\"right white hoverable  z-depth-1\" style=\"width: 300px; margin-right: 20px;\">\n");
      out.write("                <div class=\"nav-wrapper col s4\">\n");
      out.write("                    <form>\n");
      out.write("                        <div class=\"input-field\">\n");
      out.write("                            <input id=\"walkinSearch\" placeholder=\"Search\" class=\"grey-text text-darken-4\"\n");
      out.write("                                   type=\"search\" required>\n");
      out.write("                            <label for=\"walkinSearch\"><i\n");
      out.write("                                    class=\"material-icons grey-text text-darken-4\">search</i></label>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\" row col s12\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("            <div class=\"row\" align=\"left\">\n");
      out.write("\t\t        <div class=\"col s4\" ng-repeat=\"customer in vm.customerList\">\n");
      out.write("\t\t          <div class=\"card purple darken-1\">\n");
      out.write("\t\t            <div class=\"card-content white-text\">\n");
      out.write("\t\t              <span class=\"card-title\">{{customer.name}}</span>\n");
      out.write("\t\t              <p>{{customer.contact}}</p>\n");
      out.write("\t\t              <p>{{customer.strTotalPrice | currency: \"Php\"}}</p>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t            <div class=\"card-action\">\n");
      out.write("\t\t              <a href=\"#\" class=\"btn purple waves-effect waves-light\" ng-click=\"vm.moveToPay(customer.id)\">\n");
      out.write("\t\t              Move to payment</a>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t          </div>\n");
      out.write("\t\t        </div>\n");
      out.write("    \t\t</div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Modal Structure -->\n");
      out.write("    <div id=\"createWalkinModal\" class=\"modal modal-fixed-footer\"  style=\"width: 90% !important; height: 90% !important; max-height: 100% !important; margin-top: -40px;\">\n");
      out.write("        <form class=\"col s12\" id=\"createWalkinForm\" method=\"post\" action=\"\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("\n");
      out.write("                <div class=\"wrapper\">\n");
      out.write("                    <h4 class=\"center grey-text text-darken-1\">Create Walk-In<a id=\"btnCrExtraExit\" type=\"reset\"\n");
      out.write("                                                                                value=\"Reset\"\n");
      out.write("                                                                                class=\"modal-action modal-close\"><i\n");
      out.write("                            class=\"small material-icons right grey-text text-darken-4\">close</i></a></h4>\n");
      out.write("                    <div class=\"progress\">\n");
      out.write("                        <div class=\"determinate center active purple darken-4 white-text\" role=\"progressbar\"\n");
      out.write("                             aria-valuemin=\"0\"\n");
      out.write("                             aria-valuemax=\"100\" style=\"color: white;\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"walkinerrorcontainer card red center input-field col s12 white-text z-depth-barts\">\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"stepwalkin well\" style=\"margin-top: -5px;\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"container\">\n");
      out.write("                                <div class=\"input-field col s12\">\n");
      out.write("                                    <input type=\"text\" class=\"validate\" id=\"crWIName\"\n");
      out.write("                                           ng-model=\"vm.details.name\" placeholder=\"Name\"\n");
      out.write("                                           style='font-size: 22px; line-height: 15px !important;'/>\n");
      out.write("                                    <label for=\"crWIName\" class=\"active\" ><b style='font-size: 20px; line-height: 15px !important;'>Name</b><i\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"input-field col s12\">\n");
      out.write("                                    <input type=\"text\" id=\"crWIContact\" ng-model=\"vm.details.contact\" placeholder=\"contact\"\n");
      out.write("                                    \t\tstyle='font-size: 22px; line-height: 15px !important;'/>\n");
      out.write("                                    <label for=\"crWIContact\" class=\"active\"><b>Contact</b><i\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"input-field col s12\" style=\"margin-top: 15px;\">\n");
      out.write("                                    <input type=\"email\" ng-model=\"vm.details.email\" id=\"crWIEmail\" placeholder=\"Email\"\n");
      out.write("                                    \t\tstyle='font-size: 22px; line-height: 15px !important;'/>\n");
      out.write("                                    <label for=\"crWIEmail\" class=\"active\"><b>Email</b><i\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"stepwalkin well\" ng-controller=\"walkinCtrl\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col s4\">\n");
      out.write("                                <select id=\"discountFilter\" ng-model=\"vm.selected\">\n");
      out.write("                                    <option value=\"product\">Product</option>\n");
      out.write("                                    <option value=\"service\">Service</option>\n");
      out.write("                                    <option value=\"package\">Package</option>\n");
      out.write("                                    <option value=\"promo\">Promo</option>\n");
      out.write("                                </select>\n");
      out.write("                                <label for=\"discountFilter\"><b>Select</b></label>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <nav class=\"right white z-depth-1\" style=\"width: 300px; margin-right: 20px;\">\n");
      out.write("                                <div class=\"nav-wrapper col s12\">\n");
      out.write("                                    <form>\n");
      out.write("                                        <div class=\"input-field\">\n");
      out.write("                                            <input id=\"crDiscountSearch\" placeholder=\"Search\"\n");
      out.write("                                                   class=\"grey-text text-darken-4\"\n");
      out.write("                                                   type=\"search\" style=\"border: none !important;\">\n");
      out.write("                                            <label for=\"crDiscountSearch\"><i\n");
      out.write("                                                    class=\"material-icons grey-text text-darken-4\">search</i></label>\n");
      out.write("                                        </div>\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                            </nav>\n");
      out.write("                            \n");
      out.write("                            <div class=\"row col s12\">\n");
      out.write("                        \n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                             <div ng-show=\"vm.selected == 'product'\">\n");
      out.write("                                <div class=\"row \">\n");
      out.write("                                    <div class=\"col s2\" ng-repeat=\"product in vm.productList\">\n");
      out.write("                                        <div class=\"card small\">\n");
      out.write("                                            <div class=\"card-image waves-effect waves-block waves-light\">\n");
      out.write("                                                <img class=\"activator\" ng-src=\"{{product.strPhotoPath}}\">\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"card-content\">\n");
      out.write("                                                <a class=\"activator grey-text text-darken-4 light btn btn-small center\" style=\"margin-top: -10px;\"><i class=\"material-icons right white-text\">add_shopping_cart</i></a>\n");
      out.write("                                                <h5 style='font-size: 12px; line-height: 10px !important;'><b>{{product.strProductName}}</b>\n");
      out.write("                                                    <p>{{product.dblProductPrice | currency:\"P\"}}</p></h5>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"card-reveal\">\n");
      out.write("\n");
      out.write("                                                <span class=\"card-title grey-text text-darken-4\"><i\n");
      out.write("                                                        class=\"material-icons right\">close</i></span>\n");
      out.write("                                                <h4 style='font-size: 12px; line-height: 15px !important;'>\n");
      out.write("                                                    <b>{{product.strProductName}}</b><br/>\n");
      out.write("                                                    <span class=\"grey-text text-darken-4\">{{product.dblProductPrice | currency:\"Php \"}}</span>\n");
      out.write("                                                </h4>\n");
      out.write("                                                <div class=\"input-field col s12\">\n");
      out.write("                                                    <input type=\"number\" id=\"crPSQty{{product.intProductID}}\" ng-model=\"vm.quantity\"/>\n");
      out.write("                                                    <label for=\"crPSQty{{product.intProductID}}\"><b>Quantity</b></label>\n");
      out.write("                                                </div>\n");
      out.write("                                                <h6 class=\"grey-text text-darken-4\">{{product.dblProductPrice * vm.quantity | currency:\n");
      out.write("                                                    \"Php \"}}</h6>\n");
      out.write("\n");
      out.write("                                                <a class=\"waves-effect waves-light btn\" ng-click=\"vm.addToCart($index, vm.selected); vm.sumTotal()\">\n");
      out.write("                                                    <i class=\"material-icons left\" style=\"padding: 0px !important; margin: 0px !important;\">\n");
      out.write("                                                        shopping_basket</i>BUY NOW!\n");
      out.write("                                                </a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                             </div>\n");
      out.write("\n");
      out.write("                            <div ng-show=\"vm.selected == 'service'\">\n");
      out.write("                                <div class=\"row \">\n");
      out.write("                                    <div class=\"col s3\" ng-repeat=\"service in vm.serviceList\">\n");
      out.write("                                        <div class=\"card small\">\n");
      out.write("                                            <div class=\"card-image waves-effect waves-block waves-light\">\n");
      out.write("                                                <img class=\"activator\" ng-src=\"{{service.strPhotoPath}}\">\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"card-content\">\n");
      out.write("                                                <a class=\"activator grey-text text-darken-4 light btn btn-small center\" style=\"margin-top: -10px;\"><i class=\"material-icons right white-text\">add_shopping_cart</i></a>\n");
      out.write("                                                <h5 style='font-size: 12px; line-height: 10px !important;'><b>{{service.strServiceName}}</b>\n");
      out.write("                                                    <p>{{service.dblServicePrice | currency:\"P\"}}</p></h5>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"card-reveal\">\n");
      out.write("\n");
      out.write("                                                <span class=\"card-title grey-text text-darken-4\"><i\n");
      out.write("                                                        class=\"material-icons right\">close</i></span>\n");
      out.write("                                                <h4 style='font-size: 12px; line-height: 15px !important;'>\n");
      out.write("                                                    <b>{{service.strServiceName}}</b><br/>\n");
      out.write("                                                    <span class=\"grey-text text-darken-4\">{{service.dblServicePrice | currency:\"Php \"}}</span>\n");
      out.write("                                                </h4>\n");
      out.write("                                                <div class=\"input-field col s12\">\n");
      out.write("                                                   <select ng-model=\"vm.selEmployee\" id=\"cREmp\" ng-options=\"employee.strEmpFirstName for employee in vm.employeeList\"></select>\n");
      out.write("                                                    <label for=\"cREmp\"><b>Employees</b></label>\n");
      out.write("                                                </div>\n");
      out.write("\n");
      out.write("                                                 <a class=\"waves-effect waves-light btn\" ng-click=\"vm.addToCart($index, vm.selected); vm.sumTotal()\">\n");
      out.write("                                                    <i class=\"material-icons left\" style=\"padding: 0px !important; margin: 0px !important;\">\n");
      out.write("                                                        shopping_basket</i>BUY NOW!\n");
      out.write("                                                </a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div ng-show=\"vm.selected == 'package'\">\n");
      out.write("                               <div class=\"row \">\n");
      out.write("                                   <div class=\"col s2\" ng-repeat=\"package in vm.packageList\">\n");
      out.write("                                       <div class=\"card small\">\n");
      out.write("                                           <div class=\"card-image waves-effect waves-block waves-light\">\n");
      out.write("                                               <img class=\"activator\" ng-src=\"{{service.strPhotoPath}}\">\n");
      out.write("                                           </div>\n");
      out.write("                                           <div class=\"card-content\">\n");
      out.write("                                               <a class=\"activator grey-text text-darken-4 light btn btn-small center\" style=\"margin-top: -10px;\"><i class=\"material-icons right white-text\">add_shopping_cart</i></a>\n");
      out.write("                                               <h5 style='font-size: 12px; line-height: 10px !important;'><b>{{package.strPackageName}}</b>\n");
      out.write("                                                   <p>{{package.dblPackagePrice | currency:\"P\"}}</p></h5>\n");
      out.write("                                           </div>\n");
      out.write("                                           <div class=\"card-reveal\" >\n");
      out.write("\n");
      out.write("                                               <span class=\"card-title grey-text text-darken-4\"><i\n");
      out.write("                                                       class=\"material-icons right\">close</i></span>\n");
      out.write("                                               <h4 style='font-size: 12px; line-height: 15px !important;'>\n");
      out.write("                                                   <b>{{package.strPackageName}}</b><br/>\n");
      out.write("                                                    <ul ng-repeat=\"contains in vm.packageContains\">\n");
      out.write("                                                   \t\t<li>{{contains.service.strServiceName}}</li>\n");
      out.write("                                                   </ul>\n");
      out.write("                                                   <span class=\"grey-text tex \tt-darken-4\"></span>\n");
      out.write("                                               </h4>\n");
      out.write("\n");
      out.write("                                               <a class=\"waves-effect waves-light btn\" ng-click=\"vm.addToCart($index, vm.selected); vm.sumTotal()\">\n");
      out.write("                                                    <i class=\"material-icons left\" style=\"padding: 0px !important; margin: 0px !important;\">\n");
      out.write("                                                        shopping_basket</i>BUY NOW!\n");
      out.write("                                                </a>\n");
      out.write("                                           </div>\n");
      out.write("                                       </div>\n");
      out.write("                                   </div>\n");
      out.write("                               </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div ng-show=\"vm.selected == 'promo'\">\n");
      out.write("                                <div class=\"row \">\n");
      out.write("                                   <div class=\"col s2\" ng-repeat=\"promo in vm.promoList\">\n");
      out.write("                                       <div class=\"card small\">\n");
      out.write("                                           \n");
      out.write("                                           <div class=\"card-content\">\n");
      out.write("                                               <a class=\"activator grey-text text-darken-4 light btn btn-small center\" style=\"margin-top: -10px;\"><i class=\"material-icons right white-text\">add_shopping_cart</i></a>\n");
      out.write("                                               <h5 style='font-size: 12px; line-height: 10px !important;'><b>{{promo.strPromoName}}</b>\n");
      out.write("                                                   <p>{{promo.dblPromoPrice | currency:\"P\"}}</p></h5>\n");
      out.write("                                           </div>\n");
      out.write("                                           <div class=\"card-reveal\">\n");
      out.write("\n");
      out.write("                                               <span class=\"card-title grey-text text-darken-4\"><i\n");
      out.write("                                                       class=\"material-icons right\">close</i></span>\n");
      out.write("                                               <h4 style='font-size: 12px; line-height: 15px !important;'>\n");
      out.write("                                                   <b>{{promo.strPromoName}}</b><br/>\n");
      out.write("                                                   <span class=\"grey-text text-darken-4\">{{promo.dblPromoPrice | currency:\"Php \"}}</span>\n");
      out.write("                                               </h4>\n");
      out.write("                                             \n");
      out.write("                                               <a class=\"waves-effect waves-light btn\" ng-click=\"vm.addToCart($index, vm.selected); vm.sumTotal()\">\n");
      out.write("                                                    <i class=\"material-icons left\" style=\"padding: 0px !important; margin: 0px !important;\">\n");
      out.write("                                                        shopping_basket</i>BUY NOW!\n");
      out.write("                                                </a>\n");
      out.write("                                           </div>\n");
      out.write("                                       </div>\n");
      out.write("                                   </div>\n");
      out.write("                               </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"col s12 z-depth-barts white\" id=\"\">\n");
      out.write("                                <h6 class=\"center\" style=\"padding-top: -2px !important;\"><b>Selected Items</b></h6>\n");
      out.write("                                <div class=\"col s12\" id=\"pslist\"\n");
      out.write("                                     style=\"margin-top: -13px !important; margin-bottom: 5px !important;\"></div>\n");
      out.write("                            </div>\n");
      out.write("                             <div class=\"col s4\" style=\"margin-top: 10px;\">\n");
      out.write("\t\t\t                   <div class=\"input-field col s12\">\n");
      out.write("\t\t\t                       <select multiple ng-model=\"vm.selDiscounts\" id=\"crRDiscount\" ng-options=\"discount.strDiscountName for discount in vm.discountList\"></select>\n");
      out.write("\t\t\t                        <label for=\"crRDiscount\"><b>Discounts</b></label>\n");
      out.write("\t\t\t                    </div>\n");
      out.write("\t\t\t                </div>\n");
      out.write("                            <div class=\"col s4 z-depth-barts white\" style=\"margin-top: 10px;\">\n");
      out.write("                                <div class=\"col s12\">\n");
      out.write("                                    <div class=\"input-field col s12\">\n");
      out.write("                                        <p>Total:{{vm.sum}}</p>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"input-field col s12\" style=\"margin-top: 20px !important;\">\n");
      out.write("                                        <input type=\"text\" class=\"right-align prodPrice\" name=\"\" id=\"crPackPrice\"\n");
      out.write("                                               placeholder=\"Price\"/>\n");
      out.write("                                        <label for=\"crPackPrice\" class=\"active\"><b>Price</b><i\n");
      out.write("                                                class=\"material-icons red-text tiny\">error_outline</i></label>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button class=\"red-text btn-flat transparent left\" disabled\n");
      out.write("                        style=\"margin:0px !important; padding:0px !important;\"><i\n");
      out.write("                        class=\"material-icons\">error_outline</i>&nbspRequired field\n");
      out.write("                </button>\n");
      out.write("                <button type=\"button\" id=\"nextbtn\"\n");
      out.write("                        class=\"actionwalkin nextformwalkin waves-effect waves-light white-text btn-flat purple\"\n");
      out.write("                        style=\"margin-left: 3px; margin-right:3px;\">NEXT\n");
      out.write("                </button>\n");
      out.write("                <button type=\"submit\" value=\"submit\" id=\"createReservationSubmitForm\"\n");
      out.write("                        class=\"actionwalkin submitformwalkin waves-effect waves-light white-text btn-flat purple\"\n");
      out.write("                        ng-click=\"vm.saveWalkin(details)\"\n");
      out.write("                        style=\"margin-left:3px; margin-right:3px;\">CREATE\n");
      out.write("                </button>\n");
      out.write("                <button type=\"button\" id=\"backbtn\"\n");
      out.write("                        class=\"actionwalkin backformwalkin waves-effect waves-purple transparent btn-flat\"\n");
      out.write("                        style=\"margin-left: 3px;margin-right:3px;\">BACK\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div id=\"packageListModal\" class=\"modal modal-fixed-footer\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <h4 class=\"grey-text center text-darken-1\">Pacakge Contains</h4>\n");
      out.write("            <table>\n");
      out.write("            \t<tr ng-repeat=\"services in vm.packageContains\" >\n");
      out.write("            \t\t<td>{{services.service.strServiceName}}</td>\n");
      out.write("            \t\t<td> <div class=\"input-field col s12\">\n");
      out.write("                         <select ng-model=\"vm.selEmployeePerService\" id=\"cREmp1\" ng-options=\"employee.strEmpFirstName for employee in vm.employeeList\"></select>\n");
      out.write("                          <label for=\"cREmp1\"><b>Employees</b></label>\n");
      out.write("                      </div></td>\n");
      out.write("                    <td>\n");
      out.write("                    \t <button id=\"btnAssign\"\n");
      out.write("\t                    class=\"waves-effect waves-light white-text btn-flat purple\"\n");
      out.write("\t                    ng-click=\"vm.assignEmployeePackage($index)\">ASSIGN\n");
      out.write("            </button>\n");
      out.write("                    </td>\n");
      out.write("            \t</tr>\n");
      out.write("            </table>\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("            <button class=\"red-text btn-flat transparent left\" disabled\n");
      out.write("                    style=\"margin:0px !important; padding:0px !important;\"><i\n");
      out.write("                    class=\"material-icons\">error_outline</i>&nbspRequired field\n");
      out.write("            </button>\n");
      out.write("            <button type=\"submit\" value=\"Submit\" id=\"paymentDetails.submit\"\n");
      out.write("                    class=\"waves-effect waves-light white-text btn-flat purple\"\n");
      out.write("                    style=\"margin-left:3px; margin-right:3px;\"\n");
      out.write("                    ng-click=\"\">DONE\n");
      out.write("            </button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("     <div id=\"promoListModal\" class=\"modal modal-fixed-footer\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <h4 class=\"grey-text center text-darken-1\">Promo Contains</h4>\n");
      out.write("            <table>\n");
      out.write("            \t<tr ng-repeat=\"services in vm.promoContains\" >\n");
      out.write("            \t\t<td>{{services.service.strServiceName}}</td>\n");
      out.write("            \t\t<td> <div class=\"input-field col s12\">\n");
      out.write("                         <select ng-model=\"vm.selEmployeePerService\" id=\"cREmp1\" ng-options=\"employee.strEmpFirstName for employee in vm.employeeList\"></select>\n");
      out.write("                          <label for=\"cREmp1\"><b>Employees</b></label>\n");
      out.write("                      </div></td>\n");
      out.write("                    <td>\n");
      out.write("                    \t <button id=\"btnAssign\"\n");
      out.write("\t                    class=\"waves-effect waves-light white-text btn-flat purple\"\n");
      out.write("\t                    ng-click=\"vm.assignEmployeePromo($index)\">ASSIGN\n");
      out.write("            </button>\n");
      out.write("                    </td>\n");
      out.write("            \t</tr>\n");
      out.write("            </table>\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("            <button class=\"red-text btn-flat transparent left\" disabled\n");
      out.write("                    style=\"margin:0px !important; padding:0px !important;\"><i\n");
      out.write("                    class=\"material-icons\">error_outline</i>&nbspRequired field\n");
      out.write("            </button>\n");
      out.write("            <button type=\"submit\" value=\"Submit\" id=\"paymentDetails.submit\"\n");
      out.write("                    class=\"waves-effect waves-light white-text btn-flat purple\"\n");
      out.write("                    style=\"margin-left:3px; margin-right:3px;\"\n");
      out.write("                    ng-click=\"\">DONE\n");
      out.write("            </button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
