/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-08-16 21:19:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class transactions_002dproductorder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div ng-controller=\"prodSalesCtrl\">\r\n");
      out.write("    <div class=\"wrapper\" id=\"MainWrap\">\r\n");
      out.write("        <div class=\"aside asideAside1 z-depth-barts\" style=\"margin-left: 20px; margin-right: 20px;\">\r\n");
      out.write("            <div class=\"col s12\" style=\"margin-left: 20px; margin-right: 20px;\">\r\n");
      out.write("                <h3 class=\"grey-text text-darken-1\">Product Sales</h3>\r\n");
      out.write("                <a class=\"pscrbtn z-depth-1 hoverable waves-effect waves-light modal-trigger btn left green darken-2 white-text\"\r\n");
      out.write("                   href=\"#crProductSales\" style=\"margin-top: 30px; margin-left: 15px;\">CHECK OUT<i\r\n");
      out.write("                        class=\"material-icons right\">shopping_cart</i></a>\r\n");
      out.write("                <a class=\"z-depth-1 hoverable waves-effect waves-light modal-trigger btn purple darken-2 left white-text\"\r\n");
      out.write("                   href=\"#prodsalesTable\" style=\"margin-top: 30px; margin-left: 15px;\"><i\r\n");
      out.write("                        class=\"material-icons\">border_all</i></a>\r\n");
      out.write("                <nav class=\"right white hoverable  z-depth-1\" style=\"width: 40%;\">\r\n");
      out.write("                    <div class=\"nav-wrapper col s4\">\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <div class=\"input-field\">\r\n");
      out.write("                                <input id=\"psSearch\" placeholder=\"Search\" class=\"grey-text text-darken-4\" type=\"search\"\r\n");
      out.write("                                       required/>\r\n");
      out.write("                                <label for=\"psSearch\"><i\r\n");
      out.write("                                        class=\"material-icons grey-text text-darken-4\">search</i></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row col s12\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row \">\r\n");
      out.write("                <div class=\"col s3\" ng-repeat=\"product in productList\">\r\n");
      out.write("                    <div class=\"card small\">\r\n");
      out.write("                        <div class=\"card-image waves-effect waves-block waves-light\">\r\n");
      out.write("                            <img class=\"activator\" ng-src=\"{{product.strPhotoPath}}\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-content\">\r\n");
      out.write("                            <span class=\"activator grey-text text-darken-4 light\"><i class=\"material-icons right\">add_shopping_cart</i></span>\r\n");
      out.write("                            <h5 style='font-size: 15px; line-height: 15px !important;'><b>{{product.strProductName}}</b>\r\n");
      out.write("                                <p>{{product.dblProductPrice | currency:\"Php \"}}</p></h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-reveal\">\r\n");
      out.write("\r\n");
      out.write("                            <span class=\"card-title grey-text text-darken-4\"><i\r\n");
      out.write("                                    class=\"material-icons right\">close</i></span>\r\n");
      out.write("                            <h4 style='font-size: 15px; line-height: 15px !important;'>\r\n");
      out.write("                                <b>{{product.strProductName}}</b><br/>\r\n");
      out.write("                                <span class=\"grey-text text-darken-4\">{{product.dblProductPrice | currency:\"Php \"}}</span>\r\n");
      out.write("                            </h4>\r\n");
      out.write("                            <div class=\"input-field col s12\">\r\n");
      out.write("                                <input type=\"number\" id=\"crPSQty{{product.intProductID}}\" ng-model=\"details.quantity\"/>\r\n");
      out.write("                                <label for=\"crPSQty{{product.intProductID}}\"><b>Quantity</b></label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h6 class=\"grey-text text-darken-4\">{{product.dblProductPrice * details.quantity | currency:\r\n");
      out.write("                                \"Php \"}}</h6>\r\n");
      out.write("\r\n");
      out.write("                            <button class=\"waves-effect waves-light btn\" ng-click=\"addToCart($index); calculateTotal()\">\r\n");
      out.write("                                <i class=\"material-icons left\" style=\"padding: 0px !important; margin: 0px !important;\">\r\n");
      out.write("                                    shopping_basket</i>BUY NOW!\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"editItem\" class=\"modal modal-fixed-footer\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <h4 class=\"center\">{{orderToBeEdit.product}}<br/>\r\n");
      out.write("                    <img class=\"circle\" ng-src=\"{{orderToBeEdit.strPhotoPath}}\" height=\"150\" width=\"150\"></h4>\r\n");
      out.write("                <h6 class=\"center\">Price: {{orderToBeEdit.price | currency: \"Php \"}}</h6>\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"input-field col s4 offset-s4\" style=\"margin-top: -20px !important;\">\r\n");
      out.write("                            <input type=\"number\" class=\"center-align\" ng-model=\"orderToBeEdit.quantity\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-field col s12\" style=\"margin-top: -10px !important;\">\r\n");
      out.write("                            <h5 class=\"center\">Total: {{ (orderToBeEdit.price * orderToBeEdit.quantity) | currency: \"Php \"}}</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button class=\"waves-effect waves-light btn-flat purple white-text\"\r\n");
      out.write("                        ng-click=\"editInCart(orderToBeEdit)\">\r\n");
      out.write("                    SAVE\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"aside asideAside2 transparent\">\r\n");
      out.write("            <div class=\"aside white z-depth-barts\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col s12\">\r\n");
      out.write("                        <h5>Selected Item</h5>\r\n");
      out.write("                        <ul class=\"collection with-header reqList\" style=\"height: 15em !important;\">\r\n");
      out.write("                            <li class=\"collection-item left-align\" style=\"margin-left:0px !important; padding-left: 5px !important;\"\r\n");
      out.write("                                ng-repeat=\"orders in orderList\"\r\n");
      out.write("                                ng-if=\"orders.product!='' && orders.total!=0\">\r\n");
      out.write("                                <img ng-src=\"{{orders.strPhotoPath}}\" class=\"circle\" height=\"30\" width=\"30\">\r\n");
      out.write("                                <span style=\"padding-left: 5px !important;\" title=\"{{orders.product}} - {{orders.total | currency: 'Php '}}\">\r\n");
      out.write("                                    {{orders.product | truncate: 14}}\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <button name=\"\" title=\"Decline\" class=\"secondary-content red-text transparent\"\r\n");
      out.write("                                        style=\"padding: 0px !important; margin-top: -10px !important; margin-bottom: 0 !important; border:0px !important;\"\r\n");
      out.write("                                        ng-click=\"removeToCart($index, orders)\">\r\n");
      out.write("                                    <i class=\"material-icons\" style=\"padding-top: 7px !important;\">clear</i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button name=\"\" title=\"Accept\" class=\"secondary-content black-text transparent\"\r\n");
      out.write("                                        style=\"padding: 0px !important; margin-top: -10px !important; margin-bottom: 0 !important; border: 0px !important;\"\r\n");
      out.write("                                        ng-click=\"openEditItem($index, orders)\">\r\n");
      out.write("                                    <i class=\"material-icons\" style=\"padding-top: 7px !important;\">edit</i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <h5>Total: {{totalAmount | currency: \"Php \"}}</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"aside white z-depth-barts\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col s12 transparent\">\r\n");
      out.write("                        <h5>Request of</h5>\r\n");
      out.write("                        <ul class=\"collection with-header reqList\">\r\n");
      out.write("                            <li class=\"collection-item left-align\" style=\"margin-left:0px !important; padding-left: 10px !important;\"\r\n");
      out.write("                                ng-repeat=\"request in requestOrder.slice().reverse()\">\r\n");
      out.write("                                <i class=\"material-icons left\" style=\"margin-right:10px !important; margin-top: -3px !important;\"\r\n");
      out.write("                                   ng-if=\"request.intType==1 || request.intType=='delivery'\">\r\n");
      out.write("                                    local_shipping\r\n");
      out.write("                                </i>\r\n");
      out.write("                                <i class=\"material-icons left\" style=\"margin-right:10px !important; margin-top: -3px !important;\"\r\n");
      out.write("                                   ng-if=\"request.intType==2 || request.intType=='pickup'\">\r\n");
      out.write("                                    shopping_basket\r\n");
      out.write("                                </i>\r\n");
      out.write("                                <span title=\"{{ request.strName }}\">{{ request.strName | truncate: 13 }}</span>\r\n");
      out.write("                                <button name=\"\" title=\"Decline\" class=\"secondary-content red-text transparent\"\r\n");
      out.write("                                        style=\"padding: 0px !important; margin-top: -10px !important; margin-bottom: 0 !important; border:0px !important;\"\r\n");
      out.write("                                        ng-click=\"declineOrder(request)\">\r\n");
      out.write("                                    <i class=\"material-icons\" style=\"padding-top: 7px !important;\">clear</i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button name=\"\" title=\"Accept\" class=\"secondary-content black-text transparent\"\r\n");
      out.write("                                        style=\"padding: 0px !important; margin-top: -10px !important; margin-bottom: 0 !important; border: 0px !important;\"\r\n");
      out.write("                                        ng-if=\"request.intType==1 || request.intType=='delivery'\"\r\n");
      out.write("                                        ng-click=\"acceptDeliveryOrder(request)\">\r\n");
      out.write("                                    <i class=\"material-icons\" style=\"padding-top: 7px !important;\">done</i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button name=\"\" title=\"Accept\" class=\"secondary-content black-text transparent\"\r\n");
      out.write("                                        style=\"padding: 0px !important; margin-top: -10px !important; margin-bottom: 0 !important; border: 0px !important;\"\r\n");
      out.write("                                        ng-if=\"request.intType==2 || request.intType=='pickup'\"\r\n");
      out.write("                                        ng-click=\"acceptPickupOrder(request)\">\r\n");
      out.write("                                    <i class=\"material-icons\" style=\"padding-top: 7px !important;\">done</i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p>\r\n");
      out.write("                            <i class=\"material-icons\">local_shipping</i> - Delivery\r\n");
      out.write("                            <i class=\"material-icons\">shopping_basket</i> - Pick-up\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"crProductSales\" class=\"modal modal-fixed-footer\"\r\n");
      out.write("         style=\"width: 50% !important; height: 70% !important; max-height: 100% !important; margin-top: -40px;\">\r\n");
      out.write("        <form class=\"col s12\" id=\"createPSForm\" name=\"createPSForm\" method=\"post\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"wrapper\">\r\n");
      out.write("                    <h4 class=\"center grey-text text-darken-1\">Create Order\r\n");
      out.write("                        <a id=\"btnCreateExit\"\r\n");
      out.write("                           class=\"modal-action modal-close\"><i\r\n");
      out.write("                                class=\"small material-icons right grey-text text-darken-4\">close</i></a>\r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"stepps well\">\r\n");
      out.write("                            <div class=\"container\">\r\n");
      out.write("                                <div class=\"input-field col s6\">\r\n");
      out.write("                                    <select ng-options=\"order.name for order in orderType track by order.id\"\r\n");
      out.write("                                            ng-model=\"details.order\"\r\n");
      out.write("                                            id=\"crOrderType\">\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    <label for=\"crOrderType\"><b>Select</b><i\r\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s6\">\r\n");
      out.write("                                    <input type=\"text\" name=\"strOrderContact\" id=\"crOrderContact\"\r\n");
      out.write("                                           ng-model=\"details.contact\"/>\r\n");
      out.write("                                    <label for=\"crOrderContact\"><b>Contact Number</b><i\r\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s12\">\r\n");
      out.write("                                    <input type=\"text\" name=\"strOrderName\" id=\"crOrderName\" ng-model=\"details.name\"/>\r\n");
      out.write("                                    <label for=\"crOrderName\"><b>Name</b><i\r\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s6\" id=\"crDivOrderSt\">\r\n");
      out.write("                                    <input type=\"text\" name=\"strOrderStreet\" id=\"crOrderStreet\"\r\n");
      out.write("                                           ng-model=\"details.street\"/>\r\n");
      out.write("                                    <label for=\"crOrderStreet\"><b>Street</b><i\r\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s6\" id=\"crDivOrderLoc\">\r\n");
      out.write("                                    <select ng-options=\"location.strBarangay for location in locationList\"\r\n");
      out.write("                                            ng-model=\"details.location\" id=\"crOrderLoc\">\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    <label for=\"crOrderLoc\"><b>Location</b><i\r\n");
      out.write("                                            class=\"material-icons red-text tiny\">error_outline</i></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button class=\"red-text btn-flat transparent left\" disabled\r\n");
      out.write("                        style=\"margin:0px !important; padding:0px !important;\"><i\r\n");
      out.write("                        class=\"material-icons\">error_outline</i>&nbspRequired field\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"button\" class=\"actionps backformps waves-effect waves-purple transparent btn-flat\"\r\n");
      out.write("                        style=\"margin-left: 3px;margin-right:3px;\">BACK\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"button\" id=\"nextbtn\"\r\n");
      out.write("                        class=\"actionps nextformps waves-effect waves-light white-text btn-flat purple\"\r\n");
      out.write("                        style=\"margin-left: 3px; margin-right:3px;\">NEXT\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"submit\" value=\"Submit\" id=\"crCreateOrderBtn\"\r\n");
      out.write("                        class=\"actionps submitformps waves-effect waves-light white-text btn-flat purple\"\r\n");
      out.write("                        style=\"margin-left:3px; margin-right:3px;\"\r\n");
      out.write("                        ng-click=\"setProdSalesPayment(details); commaProducts(); commaQuantity()\">CREATE\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <pre>{{details | json}}</pre>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"AcceptDeliveryModal\" class=\"modal modal-fixed-footer\"\r\n");
      out.write("         style=\"width: 500px !important; height: 600px !important;\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <h4 class=\"center grey-text text-darken-3\">Set delivery date for <br/>\r\n");
      out.write("                        <span class=\"grey-text text-darken-4\"><b>{{delivery.strName | uppercase}}</b></span></h4>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"hidden\" ng-model=\"delivery.intSalesID\"/>\r\n");
      out.write("                    <input type=\"hidden\" ng-model=\"delivery.index\"/>\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"input-field col s12\" style=\"margin-top: 50px !important;\">\r\n");
      out.write("                            <input type=\"date\" name=\"delDate\" class=\"datepicker-delivery\"\r\n");
      out.write("                                   id=\"deliveryDate\" placeholder=\"August/01/2016\" required\r\n");
      out.write("                                   ng-model=\"delivery.deliveryDate\"/>\r\n");
      out.write("                            <label for=\"deliveryDate\" class=\"active\"><b>Delivery Date</b><i\r\n");
      out.write("                                    class=\"material-icons tiny red-text\">error_outline</i></label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("            <button class=\"red-text btn-flat transparent left\" disabled\r\n");
      out.write("                    style=\"margin:0px !important; padding:0px !important;\"><i\r\n");
      out.write("                    class=\"material-icons red-text\">error_outline</i>&nbspRequired field\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"submitDeliveryDate\" class=\"waves-effect waves-light white-text btn-flat purple\"\r\n");
      out.write("                    style=\"margin-left:3px; margin-right:3px;\"\r\n");
      out.write("                    ng-click=\"sendDeliveryDetails(delivery)\">\r\n");
      out.write("                PROCEED\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"prodsalesTable\" class=\"modal modal-fixed-footer\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <h4 class=\"grey-text center text-darken-1\">Product Sales</h4>\r\n");
      out.write("            <nav class=\"right white hoverable z-depth-1\" style=\"width: 300px; margin-right: 20px;\">\r\n");
      out.write("                <div class=\"nav-wrapper col s4\">\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <div class=\"input-field\">\r\n");
      out.write("                            <input id=\"psSearchBar\" placeholder=\"Search\" class=\"grey-text text-darken-4\" type=\"search\"\r\n");
      out.write("                                   ng-model=\"filterBySearch\">\r\n");
      out.write("                            <label for=\"psSearchBar\">\r\n");
      out.write("                                <i class=\"material-icons grey-text text-darken-4\">search</i>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <table id=\"psTBL\" datatable=\"ng\" dt-options=\"dtOptions\" dt-column-defs=\"dtColumnDefs\"\r\n");
      out.write("                   class=\"row-border hoverable cell-border z-depth-1\"\r\n");
      out.write("                   style=\"margin-top: -15px !important;\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th class=\"left-align\">Name</th>\r\n");
      out.write("                    <th class=\"left-align\">Address</th>\r\n");
      out.write("                    <th class=\"right-align\">Contact</th>\r\n");
      out.write("                    <th class=\"left-align\">Type</th>\r\n");
      out.write("                    <th class=\"left-align\">Status</th>\r\n");
      out.write("                    <th class=\"center-align\">Action</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tfoot>\r\n");
      out.write("                <tr style=\"border: 1px solid #bdbdbd;\">\r\n");
      out.write("                    <th class=\"left-align\">Name</th>\r\n");
      out.write("                    <th class=\"left-align\">Address</th>\r\n");
      out.write("                    <th class=\"right-align\">Contact</th>\r\n");
      out.write("                    <th class=\"left-align\">Type</th>\r\n");
      out.write("                    <th class=\"left-align\">Status</th>\r\n");
      out.write("                    <th class=\"center-align\">Action</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </tfoot>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                <tr ng-repeat=\"order in requestOrderList | filter: filterBySearch\"\r\n");
      out.write("                    ng-if=\"order.strStatus != 'REQUEST'\">\r\n");
      out.write("                    <td class=\"left-align\">{{ order.strName }}</td>\r\n");
      out.write("                    <td class=\"left-align\">{{ order.strAddress }}</td>\r\n");
      out.write("                    <td class=\"right-align\">{{ order.strContactNo }}</td>\r\n");
      out.write("                    <td class=\"left-align\">\r\n");
      out.write("                        <span ng-if=\"order.intType==1\">DELIVERY</span>\r\n");
      out.write("                        <span ng-if=\"order.intType==2\">PICK UP</span>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"left-align\">{{ order.strStatus }}</td>\r\n");
      out.write("                    <td class=\"center-align\">\r\n");
      out.write("                        <button class=\"waves-effect waves-purple btn-flat transparent red-text text-accent-4\"\r\n");
      out.write("                                style=\"padding-left: 10px;padding-right:10px; margin: 5px;\" title=\"Deactivate\"\r\n");
      out.write("                                ng-if=\"order.strStatus=='PENDING'\"\r\n");
      out.write("                                ng-click=\"deactivateOrder(order)\">\r\n");
      out.write("                            <i class='material-icons'>delete</i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button class=\"btn-flat transparent red-text text-lighten-4\"\r\n");
      out.write("                                style=\"padding-left: 10px;padding-right:10px; margin: 5px;\"\r\n");
      out.write("                                ng-if=\"order.strStatus=='COMPLETE'\"\r\n");
      out.write("                                ng-disabled=true>\r\n");
      out.write("                            <i class='material-icons'>delete</i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("            <a href=\"#!\" class=\" modal-action modal-close waves-effect waves-green btn-flat\">Close</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
