/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-09-27 17:13:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reports_002dsales_002dorder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\" ng-controller=\"reservationReportController\">\r\n");
      out.write("    \t<div class=\"main z-depth-barts\" style=\"margin-left: 20px; margin-right: 20px;\">\r\n");
      out.write("        <div class=\"col s12\" style=\"margin-left: 20px; margin-right: 20px;\">\r\n");
      out.write("            <h3 class=\" center light\">Product Purchase Reports</h3>\r\n");
      out.write("            <!--<a class=\"btnshadow hoverable z-depth-1 waves-effect waves-light modal-trigger btn-flat purple darken-2 left white-text\"-->\r\n");
      out.write("    \r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col s7\">\r\n");
      out.write("              <div class=\"card darken-1\">\r\n");
      out.write("                <div class=\"card-content white-text\">\r\n");
      out.write("                 <div id=\"containerMonthly\" style=\"min-width: 100%; height: 99%; margin: 0 auto\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-action\">\r\n");
      out.write("                  <a class=\"waves-effect waves-light btn right green darken-2\" ng-click = \"downloadMonthly()\"><i class=\"material-icons left\">file_download</i>download</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col s5\">\r\n");
      out.write("            <div class=\"card darken-1\">\r\n");
      out.write("              <div class=\"card-content white-text\">\r\n");
      out.write("               <div id=\"containerQuarterly\" style=\"min-width: 100%; height: 100%; max-width: 100%; margin: 0 auto\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-action\">\r\n");
      out.write("               <a class=\"waves-effect waves-light btn right green darken-2\"><i class=\"material-icons left\">file_download</i>download</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("          <div class=\"col s12\">\r\n");
      out.write("            <div class=\"card darken-1\">\r\n");
      out.write("              <div class=\"card-content\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                   <div class=\"input-field col s3\">\r\n");
      out.write("                       <select ng-model = \"select.yearFrom\">\r\n");
      out.write("                         <option value=\"\" disabled selected>Choose your option</option>\r\n");
      out.write("                         <option value=\"2010\">2010</option>\r\n");
      out.write("                         <option value=\"2011\">2011</option>\r\n");
      out.write("                         <option value=\"2012\">2012</option>\r\n");
      out.write("                         <option value=\"2013\">2013</option>\r\n");
      out.write("                         <option value=\"2014\">2014</option>\r\n");
      out.write("                         <option value=\"2015\">2015</option>\r\n");
      out.write("                         <option value=\"2016\">2016</option>\r\n");
      out.write("                       </select>\r\n");
      out.write("                       <label>Year From</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"input-field col s3\">\r\n");
      out.write("                       <select ng-model = \"select.yearTo\">\r\n");
      out.write("                         <option value=\"\" disabled selected>Choose your option</option>\r\n");
      out.write("                         <option value=\"2010\">2010</option>\r\n");
      out.write("                         <option value=\"2011\">2011</option>\r\n");
      out.write("                         <option value=\"2012\">2012</option>\r\n");
      out.write("                         <option value=\"2013\">2013</option>\r\n");
      out.write("                         <option value=\"2014\">2014</option>\r\n");
      out.write("                         <option value=\"2015\">2015</option>\r\n");
      out.write("                         <option value=\"2016\">2016</option>\r\n");
      out.write("                       </select>\r\n");
      out.write("                       <label>Year To</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class = \"col s2\">\r\n");
      out.write("                        <a class=\"waves-effect waves-light btn btn-large right\" ng-click = \"generate(select)\"><i class=\"material-icons left\">search</i>SHOW</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("               <div id=\"containerAnnually\" style=\"min-width: 99%; height: 99%; max-width: 100%; margin: 0 auto\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-action\">\r\n");
      out.write("                <a class=\"waves-effect waves-light btn right green darken-2\"><i class=\"material-icons left\">file_download</i>download</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
